var szGoGoVersion="2.0.0.0";var _B=0;var _C=1;var _A=2;var _E=0,_D=1,CONST_ENP_MEDIA_FILE=2,CONST_ENP_TAGSCRIPT=3;var CONST_ENP_INDEX_MEDIA_FILE=0;var CONST_ENPA_INDEX_MEDIA_ENTRY=0;var CONST_PS_PREINIT=0,CONST_PS_INIT=1,CONST_PS_READY=2,CONST_PS_RUN=3;var g_fCreatingThumbnail= 0;var CONST_DISCUSSION_GRIP_WIDTH=770;var SCROLLBARHEIGHT=20;var CONST_STARTING_EVENT="event%3d",CONST_STARTING_TIME="time%3d",CONST_AUTO_START="autostart%3d",CONST_PROFILE="profile%3d",CONST_TOCENTRY="tocentry%3d",CONST_ASXLOCATION="asxlocation%3d",CONST_PLAYERCONTROLS="playercontrols%3d",CONST_DISABLE_PRELOAD="nopreload%3d";var CONST_PREROLL_ANIMATION="progressbar.gif",CONST_PREROLL_IMGSTATIC="progresbarstatic.gif",CONST_PREROLL_LOADINGTEXT="LoadingWaitDiv_Play_NotReady",CONST_PREROLL_LOADEDTEXT="LoadingWaitDiv_Play_Ready",CONST_PREROLL_IMGLOGO="producerlogo.gif";var CONST_SLIDE_MINWIDTH=200;var CONST_PPT_CROP=2;var MAX_TOC_INDENT=4;var CONST_PPT_RATIO=1.333;var CONST_PROFILE_COOKIE="profile",CONST_TIME_COOKIE="time",CONST_VOLUME_COOKIE="volume";var CONST_KBPS=" Kbps";var g_oSCORMAPI=null;var g_InitialCSSDirectory;var CONST_LINK_SCRIPT="javascript:document.open();document.write(\"<HTML><BODY style='background-color:transparent'><A href='%1!s!' TARGET=_blank>%2!s!</A></BODY></HTML>\");document.close();";var CONST_BLANK_SCRIPT="javascript:document.open();document.write(\"<HTML><BODY style='background-color:transparent'></BODY></HTML>\");document.close();";var CONST_IMAGE_SCRIPT ="javascript:document.open();document.write(\"<HTML><BODY onload='parent.PreLoad()' onresize='parent.R()' style='background-color:transparent;overflow:hidden'><img border=0 id='im' iw=%2!s! ih=%3!s! width=%2!s! height=%3!s! style='position:absolute;visibility:hidden' mysrc='%1!s!' onload='parent.Load(this)'></BODY></HTML>\");document.close();";var CONST_IMAGE_SCRIPT_STATICSIZE ="javascript:document.open();document.write(\"<HTML><BODY  topmargin=0 leftmargin=0 style='background-color:transparent;overflow:hidden;'><img onload='parent.SizeAndShowImage(this)' iw=%2!s! ih=%3!s! width=%2!s! height=%3!s! style='position:absolute;visibility:hidden' border=0  id='im' src='%1!s!'></BODY></HTML>\");document.close();";var CONST_PREROLL_SCRIPT="javascript:document.write(\"<HTML><HEAD><script id=TPIRCSAVAJ src='%1!s!' language='JavaScript'></script></HEAD><BODY></BODY></HTML>\");document.close();";var CONST_PREROLL_CSS="javascript:document.open();document.write(\"<HTML><HEAD><LINK id=KNILCSS href='%1!s!' REL=stylesheet type=text/css></HEAD><BODY></BODY></HTML>\");document.close();";var CONST_PREROLL_EMZ="javascript:document.open();document.write(\"<HTML><BODY><IMG id=ZME src='%1!s!'></BODY></HTML>\");document.close();";var CONST_PREROLL_MSO="javascript:document.open();document.write(\"<HTML><HEAD><LINK id=KNILOSM href='%1!s!' REL=OLE-Object-Data ></HEAD><BODY></BODY></HTML>\");document.close();";var CONST_PREROLL_IMAGE_SCRIPT ="<div style='overflow:hidden'><img border=0 id='LoadingWaitDiv_Img' iw=%2!s! ih=%3!s! src='%1!s!' style='visibility:hidden' ></div>";var _WA=new Array();var _XA=new Array();var _SA=null;var _VA=null;var _YA;var _UA=null;var g_bIsNS=0;var g_nPlayStatus=CONST_PS_PREINIT;var g_bUseMP7=1
var g_bHandlingMarkerHitEvent=0;var _RA;var g_bPausedForDownload=1;var _bA=":";var g_bHasReadyStateChangeEvent=0;var g_bTrackingY=-1;var _aA=new Array();var g_szPath="";var g_szPathOrig="";var g_bPlayWhenReady=0;var g_szProfileIndex="0";var g_szASXLocation="";var g_szPlayerControls="";var g_fStartingTime=0;var g_fStartingEvent=0;var g_fStartingTOCEntry= 0;var g_bPreviewMode=0,g_bPrerollOnlyMode=0;var g_iCurrentOnClickEvent=0;var g_iCurrentSlide=-1;var g_bStatic=0;var g_bLastSlideStatic=0;var g_bForceReload=0;var g_rgrgCustomDIVLists=null;var g_rgCustomTags=new Array("WMAlignProportional","WMAlignSpacing","WMAlignBottom","WMAlignRight","WMPrerollDisplay","WMBodyWidth","WMBodyHeight","WMParentHeight");var g_rgEventTags=new Array();var g_rgTOC;var g_fIgnoreMessages=0;var g_nCurrentClock=0;var g_szDuration;var g_nTimerID=-1;var g_bUseBandwidthManagement=0;var g_bUseWebStream=0;var g_rtFilterAnimationEventsBefore=0.0;var g_bDisablePrecache=0;var g_bPauseAfterBuffer=0;var g_bPlayAfterBuffer=0;var g_bRecalcPlayerClockPosition=1;var g_nMinimumDicussionTop=310;var g_nLastTOCContentDivWidth=0;var g_nNumTimesTrySetCurrentPositon=0;var g_bCannotSeekYet=0;var g_bTOCGenerated=0;var g_bMediaFileCued=0;var g_nSeekEntryWhenOpen=-1;var g_fSeekTimeWhenOpen=-1;var g_nResizeRetries=0;var m_szProtocol="http";var g_nIgnoreThisEvent=-1;var g_bPlayWhenOpen=0;var g_nSeekToEvent=-1;var g_fFinished=0;var m_bNeedRebuildItemArray=0;var g_pBitRateWindow=null;var m_bProfileInURLParam=0;var g_bWebStreamPrerollDone=0;var g_szrgWMProtocols=new Array(
"mms","mmst","mmsu","rtsp","rtspt","rtspu","http");var MediaPlayer;var LINKLAYOUT
var ProducerLogoDiv;var ProducerLink;var ProducerLogoImg;var SlidesFrame;var HTML1Frame;var MediaPlayerDiv;var TOCContentDiv;var LoadingWaitDiv_ImgDiv;var LoadingWaitDiv_TitleDiv;var LoadingWaitDiv_PresenterDiv;var LoadingWaitDiv_DescDiv;var LoadingWaitDiv_Play;var LoadingWaitDiv_Bitrate;var LoadingWaitDiv_Anm;var LoadingWaitDiv_A;var PlayerPlayPause;var PlayerPrevious;var PlayerNext;var PlayerSkipForward;var PlayerSkipBack;var PlayerVolume;var PlayerDiscussion;var VolumeDiv;var VolumeSlider;var g_rgszHex=new Array(
"%00","%01","%02","%03","%04","%05","%06","%07","%08","%09","%0a","%0b","%0c","%0d","%0e","%0f","%10","%11","%12","%13","%14","%15","%16","%17","%18","%19","%1a","%1b","%1c","%1d","%1e","%1f","%20","%21","%22","%23","%24","%25","%26","%27","%28","%29","%2a","%2b","%2c","%2d","%2e","%2f","%30","%31","%32","%33","%34","%35","%36","%37","%38","%39","%3a","%3b","%3c","%3d","%3e","%3f","%40","%41","%42","%43","%44","%45","%46","%47","%48","%49","%4a","%4b","%4c","%4d","%4e","%4f","%50","%51","%52","%53","%54","%55","%56","%57","%58","%59","%5a","%5b","%5c","%5d","%5e","%5f","%60","%61","%62","%63","%64","%65","%66","%67","%68","%69","%6a","%6b","%6c","%6d","%6e","%6f","%70","%71","%72","%73","%74","%75","%76","%77","%78","%79","%7a","%7b","%7c","%7d","%7e","%7f","%80","%81","%82","%83","%84","%85","%86","%87","%88","%89","%8a","%8b","%8c","%8d","%8e","%8f","%90","%91","%92","%93","%94","%95","%96","%97","%98","%99","%9a","%9b","%9c","%9d","%9e","%9f","%a0","%a1","%a2","%a3","%a4","%a5","%a6","%a7","%a8","%a9","%aa","%ab","%ac","%ad","%ae","%af","%b0","%b1","%b2","%b3","%b4","%b5","%b6","%b7","%b8","%b9","%ba","%bb","%bc","%bd","%be","%bf","%c0","%c1","%c2","%c3","%c4","%c5","%c6","%c7","%c8","%c9","%ca","%cb","%cc","%cd","%ce","%cf","%d0","%d1","%d2","%d3","%d4","%d5","%d6","%d7","%d8","%d9","%da","%db","%dc","%dd","%de","%df","%e0","%e1","%e2","%e3","%e4","%e5","%e6","%e7","%e8","%e9","%ea","%eb","%ec","%ed","%ee","%ef","%f0","%f1","%f2","%f3","%f4","%f5","%f6","%f7","%f8","%f9","%fa","%fb","%fc","%fd","%fe","%ff");function encodeURL(s)
{var i,szEncoded="";for(i=0;i<s.length;i++)
{var val=s.charCodeAt(i);var ch=s.charAt(i)
if(("A".charCodeAt(0)<= val&&val<="Z".charCodeAt(0)) ||
('a'.charCodeAt(0)<=val&&val<='z'.charCodeAt(0)) ||
('0'.charCodeAt(0)<=val&&val<='9'.charCodeAt(0)) ||
(ch=='-'||ch=='_' ||ch=='.'||ch=='!'||ch=='/'||ch=='~'||ch=='*'||ch==':'||ch=='\''||ch=='('||ch==')'))
szEncoded+=ch;else if(val<=0x007f)
szEncoded+=g_rgszHex[val];else if(val<=0x07FF)
szEncoded+=g_rgszHex[0xc0 | (val >> 6)]+g_rgszHex[0x80 | (val & 0x3F)];else
szEncoded+=g_rgszHex[0xe0 | (val >> 12)]+g_rgszHex[0x80 | ((val >> 6) & 0x3F)]+g_rgszHex[0x80 | (val & 0x3F)];}return szEncoded;}function ValFromCh(ch)
{ch=ch.toLowerCase();var chCode=ch.charCodeAt(0);if('0'.charCodeAt(0)<= chCode&&chCode<='9'.charCodeAt(0))
return chCode-'0'.charCodeAt(0);return (10+(chCode-'a'.charCodeAt(0))) & 0xF;}function decodeURL(s)
{var strEnc="";var cchChars=s.length;var by,tot=0;if(URLIsDBCS(s))
return unescape(s);for(var i=0,cbRem=-1;i<cchChars;i++)
{var ch=s.charAt(i);if(ch=='%')
by=(ValFromCh(s.charAt(++i)) << 4) | ValFromCh(s.charAt(++i));else if(ch=='+')
by=' '.charCodeAt(0);else
by=ch.charCodeAt(0);if((by & 0xc0)==0x80)
{tot=(tot << 6) | (by & 0x3f);if(--cbRem==0)
strEnc+= String.fromCharCode(tot);}else if((by & 0x80)==0x00)
{strEnc+=String.fromCharCode(by);}else if((by & 0xe0)==0xc0)
{tot=by & 0x1f;cbRem=1;}else if((by & 0xf0)==0xe0)
{tot=by & 0x0f;cbRem=2;}else if((by & 0xf8)==0xf0)
{tot=by & 0x07;cbRem=3;}else if((by & 0xfc)==0xf8)
{tot=by & 0x03;cbRem=4;}else
{tot=by & 0x01;cbRem=5;}}return strEnc;}function URLIsDBCS(s)
{var szEscaped=escape(s);var re=new RegExp("%u[0123456789ABCDEF]{4}","i");return szEscaped.match(re);}function PrepareURL(szUrl)
{var fLocalFile=(m_szProtocol!="http");var fASX=(szUrl.toLowerCase().indexOf(".asx")>0);var fDBCSURL=URLIsDBCS(szUrl);if(fLocalFile&&FIEClient())
return unescape(szUrl);if(szUrl.indexOf("javascript:")>=0)
return szUrl;if(fASX)
return szUrl;return encodeURL(szUrl);}function AssignObjects()
{MediaPlayer=document.getElementById("MediaPlayer");LINKLAYOUT=document.getElementById("LINKLAYOUT");ProducerLogoDiv=document.getElementById("ProducerLogoDiv");ProducerLink=document.getElementById("ProducerLink");ProducerLogoImg=document.getElementById("ProducerLogoImg");SlidesFrame=document.getElementById("SlidesFrame");HTML1Frame=document.getElementById("HTML1Frame");MediaPlayerDiv=document.getElementById("MediaPlayerDiv");TOCContentDiv=document.getElementById("TOCContentDiv");LoadingWaitDiv_ImgDiv=document.getElementById("LoadingWaitDiv_ImgDiv");LoadingWaitDiv_TitleDiv=document.getElementById("LoadingWaitDiv_TitleDiv");LoadingWaitDiv_PresenterDiv=document.getElementById("LoadingWaitDiv_PresenterDiv");LoadingWaitDiv_DescDiv=document.getElementById("LoadingWaitDiv_DescDiv");LoadingWaitDiv_Play=document.getElementById("LoadingWaitDiv_Play");LoadingWaitDiv_Bitrate=document.getElementById("LoadingWaitDiv_Bitrate");LoadingWaitDiv_Anm=document.getElementById("LoadingWaitDiv_Anm");LoadingWaitDiv_A=document.getElementById("LoadingWaitDiv_A");PlayerPlayPause=document.getElementById("PlayerPlayPause");PlayerPrevious=document.getElementById("PlayerPrevious");PlayerNext=document.getElementById("PlayerNext");PlayerSkipForward=document.getElementById("PlayerSkipForward");PlayerSkipBack=document.getElementById("PlayerSkipBack");PlayerVolume=document.getElementById("PlayerVolume");PlayerDiscussion=document.getElementById("PlayerDiscussion");VolumeDiv=document.getElementById("VolumeDiv");VolumeSlider=document.getElementById("VolumeSlider");}function GetGoGoVersion()
{return szGoGoVersion;}function GetProjectPath()
{if(escape(window.location.search).toUpperCase()== "%3FPREVIEW")
return "";if(g_szPath!="")
return g_szPath;g_szPath=window.location.href;var nSlash=g_szPath.lastIndexOf("/");if(nSlash==-1)
nSlash=g_szPath.lastIndexOf("\\");if(nSlash!=-1)
g_szPath=g_szPath.substr(0,nSlash+1);var iTripleSlash=g_szPath.indexOf("///");if(iTripleSlash>0)
g_szPath=g_szPath.substr(0,iTripleSlash)+g_szPath.substr(iTripleSlash+1);g_szPathOrig=g_szPath;g_szPath=decodeURL(g_szPath);return g_szPath;}function PreInitialize()
{var szHash=escape(window.location.hash).toLowerCase();if(szHash.length)
{g_fStartingEvent=ExtractURLParameter(CONST_STARTING_EVENT,szHash,CONST_PARAMTYPE_INT,0);g_fStartingTime=ExtractURLParameter(CONST_STARTING_TIME,szHash,CONST_PARAMTYPE_FLOAT,0);g_fStartingTOCEntry=ExtractURLParameter(CONST_TOCENTRY,szHash,CONST_PARAMTYPE_INT,0);g_bPlayWhenReady=ExtractURLParameter(CONST_AUTO_START,szHash,CONST_PARAMTYPE_INT,0);g_bDisablePrecache=ExtractURLParameter(CONST_DISABLE_PRELOAD,szHash,CONST_PARAMTYPE_INT,0);g_szASXLocation=ExtractURLParameter(CONST_ASXLOCATION,szHash,CONST_PARAMTYPE_STRING,"");g_szPlayerControls=ExtractURLParameter(CONST_PLAYERCONTROLS,szHash,CONST_PARAMTYPE_STRING,"");if(g_fStartingEvent>0||g_fStartingTime>0.0||g_fStartingTOCEntry>0)
g_bPlayWhenReady=1;var nProfileIndex=ExtractURLParameter(CONST_PROFILE,szHash,CONST_PARAMTYPE_INT,-1);if(nProfileIndex!=-1)
{m_bProfileInURLParam=1;g_szProfileIndex=nProfileIndex.toString();}}if(!m_bProfileInURLParam)
{var szProfile=ReadCookie(CONST_PROFILE_COOKIE);if(szProfile!="")
{g_szProfileIndex=szProfile;}}m_szProtocol=window.location.protocol.substr(0,4).toLowerCase();InitializeProject();}function Initialize()
{AssignObjects();InitializeGoGoProd();}function Uninitialize()
{UninitializeGoGoProd();UninitializeSCORM();}function InitializeGoGoProd()
{g_nPlayStatus=CONST_PS_INIT;g_InitialCSSDirectory=g_InitialCSSFile.substr(0,g_InitialCSSFile.indexOf("/"));var _cB=escape(window.location.search);_cB=_cB.toUpperCase();if(_cB=="%3FPREVIEW")
{g_bPreviewMode=1;}else if(_cB=="%3FPREROLL")
{g_bPrerollOnlyMode=1;}else if(_cB=="%3FTHUMBNAIL")
{g_fCreatingThumbnail= 1;SlidesDiv.style.visibility="visible";SlidesDiv.innerHTML="<img src=Slide.jpg id=\"SlidesFrame\" width=100% height=100% align=\"middle\">";HTML1Div.style.visibility="visible";HTML1Div.innerHTML="<img src=HTML.jpg id=\"HTML1Frame\" width=100% height=100% align=\"middle\">";}_v();document.title=UnescapeHTML(g_szLoadingTitleNoEscape);if(_F())
{if(!g_bPreviewMode&&!g_bPrerollOnlyMode&&m_szProtocol=="http"&&!g_bDisablePrecache&&(ClientCaps & Browser_CanBandwidthManage))
g_bUseBandwidthManagement=1;}if (!g_bPreviewMode &&
(ProfileSupportsWebStreaming(g_szProfileIndex) &&
(ClientCaps & Player_SupportsWebStreaming)))
{g_bUseBandwidthManagement=0;g_bUseWebStream=1;}if(!g_bPreviewMode&&!g_bPrerollOnlyMode&&!g_fCreatingThumbnail)
{if(g_fStartingTime<=0.0)
{var szCookieTime=ReadCookie(CONST_TIME_COOKIE);var fCookieTime=parseFloat(szCookieTime);if(fCookieTime>0.0)
{g_fStartingTime=fCookieTime;}}}if(!g_bPreviewMode&&!g_bPrerollOnlyMode&&!g_fCreatingThumbnail)
{var vol=ReadCookie(CONST_VOLUME_COOKIE);if(vol!="")
MediaPlayer_SetVolume(parseFloat(vol));}if(g_fStartingEvent>0)
g_fStartingTime=_WA[g_fStartingEvent].fTime;if(g_fStartingTOCEntry>0)
g_fStartingTime=FindTOCEntry(g_fStartingTOCEntry);if(g_oSCORMAPI==null)
InitializeSCORM();if(g_oSCORMAPI)
{var fTime=g_oSCORMAPI.LMSGetValue("cmi.core.lesson_location");if(fTime!="")
{g_fStartingTime=parseFloat(fTime);}else
g_fStartingTime=0;var vol=g_oSCORMAPI.LMSGetValue("cmi.student_preference.audio");if(vol!="")
{MediaPlayer_SetVolume(parseFloat(vol));}}g_szDuration=_BA(g_nDuration);UpdateCSSFile(g_InitialCSSFile);setTimeout("InitializeGoGoProdPartDeux()",250);}function InitializeGoGoProdPartDeux()
{if(!FNetscapeClient()&& LINKLAYOUT.readyState!="complete")
{setTimeout("InitializeGoGoProdPartDeux()",250);return;}InitCustomDIVTagLists();PrerollScreen_SetStatus();if(ClientCaps & Browser_SupportsFancyPlayerButtons)
{MediaPlayer_SetButtonImageInternal(PlayerPlayPause,"PlayerPlayPause_Rest");MediaPlayer_SetButtonImageInternal(PlayerPrevious,"PlayerPrevious_Rest");MediaPlayer_SetButtonImageInternal(PlayerNext,"PlayerNext_Rest");MediaPlayer_SetButtonImageInternal(PlayerDiscussion,"PlayerDiscussion_Rest");MediaPlayer_SetButtonImageInternal(PlayerSkipForward,"PlayerSkipForward_Rest");MediaPlayer_SetButtonImageInternal(PlayerSkipBack,"PlayerSkipBack_Rest");MediaPlayer_SetButtonImageInternal(PlayerVolume,"PlayerVolume_Rest");}else
document.getElementById("MediaPlayerControlsDiv").style.display="none";document.getElementById("ProducerLogoDiv").style.visibility=g_szProducerLink!="" ? "visible":"hidden";if(g_szProducerLink!="")
{document.getElementById("ProducerLink").href=g_szProducerLink;document.getElementById("ProducerLogoImg").src=CONST_PREROLL_IMGLOGO;}if(!g_bPrerollOnlyMode)
{_x();if(!g_bPreviewMode&&(ClientCaps & Player_64ObjectModel))
{GetProjectPath();if(URLIsDBCS(g_szPathOrig)&& MediaPlayer_GetVersion()<7.0)
{if(confirm(UnescapeHTML(g_szNonAsciiPathMsg)))
navigate(g_szWMPURL);}}}if(g_fCreatingThumbnail)
{setTimeout("window.external.CaptureThumbnail()",1);}}function InitCustomDIVTagLists()
{if(g_rgrgCustomDIVLists||!(ClientCaps & Browser_SupportsCustomCSSTags))
return;g_rgrgCustomDIVLists=new Array();var i,j,pTags=document.all.tags("DIV");var nCustomTagsLen=g_rgCustomTags.length;for(i=0;i<pTags.length;i++)
{var pDIV=pTags(i);for(j=0;j<nCustomTagsLen;j++)
{if(pDIV.currentStyle.getAttribute(g_rgCustomTags[j]))
{if(!g_rgrgCustomDIVLists[g_rgCustomTags[j]])
g_rgrgCustomDIVLists[g_rgCustomTags[j]]=new Array();g_rgrgCustomDIVLists[g_rgCustomTags[j]][g_rgrgCustomDIVLists[g_rgCustomTags[j]].length]=pDIV;}}}}function ReadCookie(szKey)
{var szCookie=document.cookie;if(!szKey||szKey=="")
return szCookie;var rgValues=szCookie.split(";");var i,nValues=rgValues.length;var re=new RegExp(szKey,"i");for(i=0;i<nValues;i++)
{var szParam=Unescape(rgValues[i]);var _xA=szParam.indexOf("=");if (_xA>0 &&
szParam.length>_xA &&
szParam.substr(0,_xA).search(re)!=-1)
{return szParam.substr(_xA+1);}}return "";}function WriteCookie(szKey,_gB)
{var expireDate=new Date();expireDate.setYear(expireDate.getYear()+100);document.cookie=escape(szKey)+"="+escape(_gB)+";expires="+expireDate.toGMTString();}function UninitializeGoGoProd()
{if(!g_bPreviewMode&&!g_bPrerollOnlyMode&&!g_fCreatingThumbnail)
{var fTime=GetPresentationTime();WriteCookie(CONST_TIME_COOKIE,fTime.toString());if(g_oSCORMAPI)
{g_oSCORMAPI.LMSSetValue("cmi.core.lesson_location",fTime.toString());}}MediaPlayer_StopClock();}function _x()
{if(Technology & Technology_Mac||Technology & Technology_Netscape)
{MediaPlayer.PositionChange=MediaPlayer_PositionChange;MediaPlayer.PlayStateChange=MediaPlayer_PlayStateChange;MediaPlayer.scriptCommand=MediaPlayer_ScriptCommand;MediaPlayer.buffering=MediaPlayer_Buffering;MediaPlayer.openStateChange=MediaPlayer_OpenStateChange;if(ClientCaps & Player_64ObjectModel)
{MediaPlayer.Error=MediaPlayer_OnError;MediaPlayer.Warning=MediaPlayer_OnWarning;}LINKLAYOUT.onreadystatechange=LinkLayout_OnReadyStateChange;SlidesFrame.onreadystatechange=SlidesFrame_OnReadyStateChange;HTML1Frame.onreadystatechange=HTML1Frame_OnReadyStateChange;document.onstop= Document_OnStop;}else
{MediaPlayer.attachEvent("PositionChange",MediaPlayer_PositionChange);MediaPlayer.attachEvent("PlayStateChange",MediaPlayer_PlayStateChange);MediaPlayer.attachEvent("scriptCommand",MediaPlayer_ScriptCommand);MediaPlayer.attachEvent("buffering",MediaPlayer_Buffering);MediaPlayer.attachEvent("openStateChange",MediaPlayer_OpenStateChange);MediaPlayer.attachEvent("Error",MediaPlayer_OnError);MediaPlayer.attachEvent("Warning",MediaPlayer_OnWarning);LINKLAYOUT.attachEvent("onreadystatechange",LinkLayout_OnReadyStateChange);SlidesFrame.attachEvent("onreadystatechange",SlidesFrame_OnReadyStateChange);HTML1Frame.attachEvent("onreadystatechange",HTML1Frame_OnReadyStateChange);document.attachEvent("onstop",Document_OnStop);if(ClientCaps & Player_SupportsScriptTriggers)
{MediaPlayer.InvokeURLs=0;}if(!(ClientCaps & Player_64ObjectModel))
{MediaPlayer.attachEvent("CurrentItemChange",MediaPlayer_CurrentItemChange);}}if(g_bUseBandwidthManagement&&_XA.length>0)
{_f();}else
{if(g_nPlayStatus<CONST_PS_READY)
g_nPlayStatus=CONST_PS_READY;_t();}}function Document_OnStop()
{g_bUseBandwidthManagement=0;if(g_nPlayStatus<CONST_PS_READY)
{g_nPlayStatus=CONST_PS_READY;_t();}g_nIgnoreThisEvent=-1;}function _t()
{_z();CalculateBestProfileForBandwidth();PrerollScreen_SetStatus();if(!g_bPreviewMode)
{_WA[g_fStartingEvent].CueMediaFile();}SlidesFrame.src=CONST_BLANK_SCRIPT;HTML1Frame.src=CONST_BLANK_SCRIPT;if(g_bPreviewMode||g_bPlayWhenReady)
{StartPresentation();}}function StartPresentation()
{if(event)
event.returnValue=0;if(g_bPrerollOnlyMode)
return;_z();if(!g_bPreviewMode)
{_WA[g_fStartingEvent].CueMediaFile();}g_nPlayStatus=CONST_PS_RUN;PrerollScreen_SetStatus();if(g_strESerivceDiv.length>0)
{EServiceDIV.insertAdjacentHTML("afterBegin",Unescape(g_strESerivceDiv));try
{EServiceInit();}catch(e)
{}}if(!g_bPreviewMode)
{g_bPauseAfterBuffer=0;MediaPlayer_Play();}MediaPlayer_StartClock();if(g_fStartingTime!=0)
SetPresentationTime(g_fStartingTime,0);else
{if(g_bPreviewMode)
g_fStartingTime=MediaPlayer_GetCurrentPosition();SetPresentationTime(g_fStartingTime,1);}}function Window_OnResize()
{if(!PrerollScreen_DisplayTags())
{g_nResizeRetries++;if(g_nResizeRetries<8)
setTimeout("Window_OnResize()",400);else
g_nResizeRetries=0;return;}if(g_nPlayStatus==CONST_PS_RUN||g_fCreatingThumbnail)
{try
{MediaPlayer_OnResize();}catch(e)
{g_nResizeRetries++;if(g_nResizeRetries<10)
setTimeout("Window_OnResize()",200);else
g_nResizeRetries=0;return;}g_nResizeRetries=0;if(ClientCaps & Browser_SupportsCustomCSSTags)
{var i,j;if(g_rgrgCustomDIVLists&&g_rgrgCustomDIVLists["WMAlignProportional"])
{for(i=0;g_rgrgCustomDIVLists&&i<g_rgrgCustomDIVLists["WMAlignProportional"].length;i++)
{var pAlignRightTag=g_rgrgCustomDIVLists["WMAlignProportional"][i];var _CB=document.body.clientWidth-_o(pAlignRightTag)-pAlignRightTag.currentStyle.WMAlignProportional;var _oA=_CB / CONST_PPT_RATIO;if(_p(pAlignRightTag)+ _oA>document.body.clientHeight)
{_oA=document.body.clientHeight-_p(pAlignRightTag)-pAlignRightTag.currentStyle.WMAlignProportional;_CB=_oA*CONST_PPT_RATIO;}if((_CB>CONST_SLIDE_MINWIDTH)&& (_oA>=1))
{pAlignRightTag.runtimeStyle.width=_CB;pAlignRightTag.runtimeStyle.height=_oA;var _CB=_CB-CONST_PPT_CROP;var _oA=_oA-CONST_PPT_CROP;pAlignRightTag.runtimeStyle.clip='rect(0px '+_CB+'px '+_oA+'px 0px)';if(g_rgrgCustomDIVLists["WMAlignSpacing"])
{for(j=0;g_rgrgCustomDIVLists&&j<g_rgrgCustomDIVLists["WMAlignSpacing"].length;j++)
{var dvtag=g_rgrgCustomDIVLists["WMAlignSpacing"][j];var nSpace=GetStyleValue_Integer(dvtag.currentStyle.WMAlignSpacing);if(nSpace)
{dvtag.runtimeStyle.top=_oA+_p(pAlignRightTag)+nSpace;dvtag.runtimeStyle.width=_CB;}}}}}}if(g_rgrgCustomDIVLists&&g_rgrgCustomDIVLists["WMAlignBottom"])
{for(i=0;g_rgrgCustomDIVLists&&i<g_rgrgCustomDIVLists["WMAlignBottom"].length;i++)
{var pDivTag=g_rgrgCustomDIVLists["WMAlignBottom"][i];var _oA=document.body.clientHeight-_p(pDivTag)-pDivTag.currentStyle.WMAlignBottom;if(_oA>=1)
{pDivTag.runtimeStyle.height=_oA;}}}if(g_rgrgCustomDIVLists&&g_rgrgCustomDIVLists["WMAlignRight"])
{for(i=0;g_rgrgCustomDIVLists&&i<g_rgrgCustomDIVLists["WMAlignRight"].length;i++)
{var pDivTag=g_rgrgCustomDIVLists["WMAlignRight"][i];var _CB=document.body.clientWidth-_o(divtag)-pDivTag.currentStyle.WMAlignRight;if(_CB>=CONST_SLIDE_MINWIDTH)
{pDivTag.runtimeStyle.width=_CB;}}}if(!g_rgrgCustomDIVLists)
{g_nResizeRetries++;if(g_nResizeRetries<8)
setTimeout("Window_OnResize()",500);else
g_nResizeRetries=0;return;}}if(TOCContentDiv.clientWidth!=g_nLastTOCContentDivWidth)
EllipsifyTOC();g_nLastTOCContentDivWidth=TOCContentDiv.clientWidth;}else (g_nPlayStatus==CONST_PS_INIT)
{setTimeout("PrerollImageResize()",1);}SetDynamicDivDimensions();g_nResizeRetries=0;}function RemoveCustomDIVAttributes()
{if(!g_rgrgCustomDIVLists||!(ClientCaps & Browser_SupportsCustomCSSTags))
return;var i,j;for(j=0;j<g_rgCustomTags.length;j++)
{if(g_rgrgCustomDIVLists[g_rgCustomTags[j]])
{for(i=0;i<g_rgrgCustomDIVLists[g_rgCustomTags[j]].length;i++)
{var pTag=g_rgrgCustomDIVLists[g_rgCustomTags[j]][i];pTag.runtimeStyle.removeAttribute("width",0);pTag.runtimeStyle.removeAttribute("height",0);pTag.runtimeStyle.removeAttribute("top",0);pTag.runtimeStyle.removeAttribute("left",0);pTag.runtimeStyle.clip='rect(auto auto auto auto)';}}}for(i=0;i<document.anchors.length;i++)
{document.anchors[i].runtimeStyle.removeAttribute("backgroundImage",0);}g_rgrgCustomDIVLists=null;}function Window_OnScroll()
{if(ClientCaps & Browser_SupportsCustomCSSTags)
{SetDynamicDivDimensions();document.recalc(1);}}function TimeIntoSlide(fTime)
{var i,_cA=_WA.length;fTimeLast=0.0;for(i=0;i<_cA&&_WA[i].fTime<=fTime;i++)
{param=_WA[i].GetParamByName("SLIDECLICK");if(param!=null)
{if(param._gB.indexOf("0,")==0)
fTimeLast=_WA[i].fTime;}}fTimeDelta=fTime-fTimeLast;if(fTimeDelta<0)
fTimeDelta=0;return fTimeDelta;}function SyncSlideAnimTime()
{if(!(ClientCaps & Browser_CanControlPPTAnimationEngine))
return;try
{fTimeLocal=TimeIntoSlide(MediaPlayer_GetCurrentPosition());GetSlidesFrame().document.body.pause();GetSlidesFrame().document.body.localTime=fTimeLocal;if(MediaPlayer_IsPlaying())
GetSlidesFrame().document.body.resume();}catch(e){}}function PauseSlide()
{if(!(ClientCaps & Browser_CanControlPPTAnimationEngine))
return;try
{SyncSlideAnimTime();GetSlidesFrame().document.body.pause();}catch(e){}}function PlaySlide()
{if(!(ClientCaps & Browser_CanControlPPTAnimationEngine))
return;try
{SyncSlideAnimTime();GetSlidesFrame().document.body.resume();}catch(e){}}function MediaPlayer_GetVersion()
{var pWMP=null;var ver=6.4;try
{pWMP=new ActiveXObject("WMPlayer.OCX.7")
if(!pWMP)
throw "No player";strVer=pWMP.versionInfo;ver=parseFloat(strVer.substr(0,strVer.indexOf(".")+2));pWMP=null;}catch(e)
{pWMP=null;}return ver;}function MediaPlayer_Create()
{var _aB="";AssignObjects();if(window.location.search.indexOf("?PREVIEW")>-1)
{SetPlayerObjectModel(Player_64ObjectModel);var _aB="<OBJECT classid=\""+g_FakePlayerCLSID+"\" id=\"MediaPlayer\" width=320 height=240 align=\"middle\"></OBJECT>";AssignObjects();MediaPlayerDiv.innerHTML+=_aB;}else if(window.location.search=="?THUMBNAIL")
{MediaPlayerDiv.innerHTML+="<img src=Video.jpg id=\"MediaPlayer\" width=320 height=240 align=\"middle\">";AssignObjects();}else if(!(ClientCaps & Browser_SupportsActiveX))
{szMediaFile=encodeURL(_WA[0].GetMediaFilename());SetPlayerObjectModel(Player_64ObjectModel);if((!(Technology & Technology_Netscape))&&szMediaFile.indexOf("file://")==0)
document.getElementById("MediaPlayerDiv").innerHTML +="<OBJECT ID=\"MediaPlayer\" name=\"MediaPlayer\" height=240 width=320 CLASSID=\"CLSID:22D6f312-B0F6-11D0-94AB-0080C74C7E95\" STANDBY=\"Loading Windows Media Player components...\" TYPE=\"application/x-oleobject\"  CODEBASE=\"http://activex.microsoft.com/activex/controls/mplayer/en/nsmp2inf.cab#Version=5,1,52,701\"><PARAM NAME=\"ShowControls\" VALUE=\"Full\"> <PARAM NAME=\"AutoRewind\" VALUE=\"False\"> <PARAM NAME=\"AutoStart\" VALUE=\"1\"><PARAM NAME=\"AutoSize\" VALUE=\"0\"> <PARAM NAME=\"defaultframe\" VALUE=\"hiddenFrame\"> <param name=\"FileName\" value=\""+szMediaFile+"\"></OBJECT>";else
document.getElementById("MediaPlayerDiv").innerHTML +="<EMBED type=\"application/x-mplayer2\" SRC=\""+szMediaFile+"\" pluginspage=\"http://www.microsoft.com/Windows/MediaPlayer/\" name=MediaPlayer id=MediaPlayer height=240 width=320 ShowStatusBar=0 defaultframe=hiddenFrame></EMBED>";AssignObjects();}else
{var pWMP=null;try
{if(ClientCaps & Player_70ObjectModel)
pWMP=new ActiveXObject("WMPlayer.OCX.7")
if(!pWMP)
throw "No player";strVer=pWMP.versionInfo;if(parseInt(strVer.substr(0,strVer.indexOf(".")))>=9)
ClientCaps |= Player_SupportsWebStreaming;else
ClientCaps &=~Player_SupportsWebStreaming;szUIMode="none";if(g_szPlayerControls.toUpperCase()=="FULL"||g_szPlayerControls.toUpperCase()=="MINI")
{szUIMode=g_szPlayerControls;ClientCaps &= ~Browser_SupportsFancyPlayerButtons;}pWMP=null;_aB="<OBJECT classid=CLSID:6BF52A52-394A-11d3-B153-00C04F79FAA6  height=240 width=320 id=MediaPlayer name=MediaPlayer type=application/x-oleobject standby=\"\"> <PARAM NAME=\"URL\" VALUE=\"\"><PARAM NAME=\"autoStart\" VALUE=\"0\"><PARAM NAME=\"invokeURLs\" VALUE=\"0\"><PARAM NAME=\"baseURL\" VALUE=\"\"><PARAM NAME=\"volume\" VALUE=\"100\"><PARAM NAME=\"mute\" VALUE=\"0\"><PARAM NAME=\"uiMode\" VALUE=\""+szUIMode+"\"><PARAM NAME=\"enabled\" VALUE=\"-1\"><PARAM NAME=\"enableContextMenu\" VALUE=\"-1\"><PARAM NAME=\"captioningID\" VALUE=\"Misc8Div\"></OBJECT>";AssignObjects();MediaPlayerDiv.innerHTML+=_aB;}catch(e)
{pWMP=new ActiveXObject("MediaPlayer.MediaPlayer.1");try
{if(!pWMP)
throw e;pWMP=null;SetPlayerObjectModel(Player_64ObjectModel);szShowControls="0";if(g_szPlayerControls.toUpperCase()=="FULL" ||
g_szPlayerControls.toUpperCase()=="MINI")
{szShowControls="1";ClientCaps &= ~Browser_SupportsFancyPlayerButtons;}var _aB="<OBJECT ID=\"MediaPlayer\" name=\"MediaPlayer\" height=240 width=320 CLASSID=\"CLSID:22D6f312-B0F6-11D0-94AB-0080C74C7E95\" STANDBY=\"Loading Windows Media Player components...\" TYPE=\"application/x-oleobject\"  CODEBASE=\"http://activex.microsoft.com/activex/controls/mplayer/en/nsmp2inf.cab#Version=5,1,52,701\"><PARAM NAME=\"ShowControls\" VALUE=\""+szShowControls+"\"> <PARAM NAME=\"AutoRewind\" VALUE=\"False\"> <PARAM NAME=\"AutoStart\" VALUE=\"0\"><PARAM NAME=\"AutoSize\" VALUE=\"0\"></OBJECT>";AssignObjects();MediaPlayerDiv.innerHTML+=_aB;}catch(e)
{if(window.confirm(UnescapeHTML(g_szNoMediaPlayer)))
navigate(g_szWMPURL);else
navigate("about:blank");}}}}function MediaPlayer_EnableErrorDialogs(bEnabled)
{if(ClientCaps & Player_64ObjectModel)
{MediaPlayer.SendErrorEvents=!bEnabled;MediaPlayer.SendWarningEvents=!bEnabled;}else
{MediaPlayer.settings.enableErrorDialogs=bEnabled;}}function MediaPlayer_StartClock()
{if(g_nTimerID==-1)
{MediaPlayer_UpdatePlayerClock(-1);g_nTimerID=setInterval("MediaPlayer_UpdatePlayerClock(-1)",1000);}}function MediaPlayer_StopClock()
{if(g_nTimerID!=-1)
{clearInterval(g_nTimerID);g_nTimerID=-1;}}function MediaPlayer_Buffering(bStart)
{if(bStart)
{window.status=g_szBufferingStatus;}else
{window.status="";if(g_bPauseAfterBuffer)
{setTimeout("MediaPlayer_Pause();",1);g_bPauseAfterBuffer=0;}if(g_bPlayAfterBuffer)
{setTimeout("MediaPlayer_Play()",1);g_bPlayAfterBuffer=0;}if(ClientCaps & Player_64ObjectModel)
{if(g_nSeekEntryWhenOpen!=-1)
{MediaPlayer_SetCurrentLocation(g_nSeekEntryWhenOpen,g_fSeekTimeWhenOpen);g_nSeekEntryWhenOpen=-1;if(g_fStartingTime<=0.0)
g_fIgnoreMessages=0;}else if(g_fSeekTimeWhenOpen!=-1)
{MediaPlayer_SetCurrentLocation(g_nSeekEntryWhenOpen,g_fSeekTimeWhenOpen);g_fSeekTimeWhenOpen=-1;g_fIgnoreMessages=0;}}}}function MediaPlayer_OnError()
{var hr=MediaPlayer_ErrorCode();if(hr==-2147220968)
{if(window.confirm(UnescapeHTML(g_szNoMediaPlayer)))
navigate(g_szWMPURL);else
navigate("about:blank");}else if(hr==-2146828283&&g_fIgnoreMessages)
{}}function MediaPlayer_OnWarning(lType,lParam,sDescription)
{}function InvalidateWebStreamPreroll()
{g_bWebStreamPrerollDone=0;}function MediaPlayer_CurrentItemChange()
{InvalidateWebStreamPreroll();}function MediaPlayer_OpenStateChange(lNewState)
{if(((ClientCaps & Player_70ObjectModel)&& lNewState==13))
{if(g_nSeekEntryWhenOpen!=-1)
{MediaPlayer_SetCurrentLocation(g_nSeekEntryWhenOpen,g_fSeekTimeWhenOpen);if(g_fStartingTime<=0.0)
g_fIgnoreMessages=0;if(g_bPauseAfterBuffer&&!IsPresentationStreaming())
{setTimeout("MediaPlayer_Pause()",1);g_bPauseAfterBuffer=0;}}else if(g_fStartingTime>0.0&&g_fSeekTimeWhenOpen!=-1)
{MediaPlayer_SetCurrentLocation(g_nSeekEntryWhenOpen,g_fSeekTimeWhenOpen);g_fIgnoreMessages=0;}g_nSeekEntryWhenOpen=-1;g_fSeekTimeWhenOpen=-1;}else if((ClientCaps & Player_64ObjectModel)&& lNewState==5&&g_bPlayWhenOpen)
{setTimeout("MediaPlayer_Play()",1);g_bPlayWhenOpen=0;g_nSeekEntryWhenOpen=-1;g_fSeekTimeWhenOpen=-1;}try
{if((ClientCaps & Player_64ObjectModel)&& lNewState==5)
{var i;for(i=1;i<=MediaPlayer.CodecCount;i++)
{if(!MediaPlayer.GetCodecInstalled(i))
{alert(UnescapeHTML(g_szNoCodec +"  "+ MediaPlayer.GetCodecDescription(i)+"("+MediaPlayer.GetCodecURL(i)+")"));break;}}}}catch(e)
{ }}function MediaPlayer_ClearErrors()
{if(ClientCaps & Player_70ObjectModel)
MediaPlayer.error.clearErrorQueue();}function MediaPlayer_OnResize()
{if(!(ClientCaps & Browser_SupportsFancyPlayerButtons))
return;if(g_nPlayStatus==CONST_PS_RUN||g_fCreatingThumbnail)
{MediaPlayerControlsDiv.style.visibility="hidden";var _CB=MediaPlayerControlsDiv.offsetWidth;var nOffset=GetStyleValue_Integer(MediaPlayerControlsDiv.currentStyle.WMPlayerClockOffset);var nBLLeft=PlayerBL.offsetLeft;var nBLWidth=PlayerBL.offsetWidth;var nBLHeight=PlayerBL.offsetHeight;var nBRWidth=PlayerBR.offsetWidth;PlayerBR.style.left=_CB-(nBLLeft+nBRWidth);PlayerBC.style.width=_CB-(nBLWidth+nBRWidth);PlayerBC.style.height=nBLHeight;if(g_bRecalcPlayerClockPosition)
{PlayerClock.style.left=_CB-PlayerClock.offsetWidth-nBRWidth+nOffset;if(PlayerClock.offsetWidth>50)
PlayerClock.style.visibility="visible";g_nMinimumDicussionTop=MediaPlayerDiv.offsetTop+MediaPlayerDiv.offsetHeight+PlayerBC.offsetHeight+2;if(GetStyleValue_Integer(DiscussionDiv.style.top)<GetStyleValue_Integer(g_nMinimumDicussionTop))
{DiscussionDiv.style.top=g_nMinimumDicussionTop;SetDivContentHeight();}g_bRecalcPlayerClockPosition=0;}MediaPlayerControlsDiv.style.visibility="visible";}}function MediaPlayer_SetCurrentPosition(_FA,bAndPlay)
{g_fIgnoreMessages=1;if(ClientCaps & Player_70ObjectModel)
{if(MediaPlayer_CanSeek())
MediaPlayer.Controls.currentPosition=_FA;else
g_nIgnoreThisEvent=-1;}else
{if(g_bPreviewMode)
{MediaPlayer.CurrentPosition=_FA;}else
{if(MediaPlayer.CanSeek)
{g_nNumTimesTrySetCurrentPositon=0;if(bAndPlay)
MediaPlayer.Play();if(MediaPlayer.CurrentPosition!=_FA)
setTimeout("MediaPlayer.CurrentPosition="+_FA+";",1);MediaPlayer_UpdateControls(MediaPlayer.playState);}else if(g_nNumTimesTrySetCurrentPositon<20)
{var szMediaFile=_WA[0].GetMediaFilename();if(IsProtocolMMS(szMediaFile.substr(0,5).toLowerCase())||m_szProtocol!="http")
{setTimeout("MediaPlayer_SetCurrentPosition("+_FA+","+bAndPlay+");",500);g_nNumTimesTrySetCurrentPositon++;}g_nIgnoreThisEvent=-1;}else
{g_nNumTimesTrySetCurrentPositon=0;}}}g_fIgnoreMessages=0;}function IsProtocolMMS(szURL)
{var _pA=szURL.indexOf(":");if(_pA>0)
{var i,szProtocol=szURL.substr(0,_pA);szProtocol=szProtocol.toLowerCase();for(i=0;i<g_szrgWMProtocols.length;i++)
{if(szProtocol==g_szrgWMProtocols[i])
return 1;}}return 0;}function MediaPlayer_GetCurrentPosition()
{if(ClientCaps & Player_70ObjectModel)
return MediaPlayer.Controls.currentPosition;else
return MediaPlayer.CurrentPosition;}function MediaPlayer_CanSeek()
{if(ClientCaps & Player_70ObjectModel)
return MediaPlayer.Controls.isAvailable("CurrentPosition");else
return MediaPlayer.CanSeek;}function MediaPlayer_PlayPause()
{if(ClientCaps & Player_70ObjectModel)
{if(MediaPlayer.PlayState==3)
{MediaPlayer.Controls.Pause();PauseSlide();}else
{MediaPlayer.Controls.Play();PlaySlide();}}else
{if(MediaPlayer.PlayState==2)
{MediaPlayer.Pause();PauseSlide();}else
{MediaPlayer.Play();PlaySlide();}}}function MediaPlayer_Play()
{if(ClientCaps & Player_70ObjectModel)
{var _AB=MediaPlayer.PlayState;if(_AB==1||_AB==2||_AB==3||_AB==10)
{MediaPlayer.Controls.Play();PlaySlide();return 1;}return 0;}else
{var _AB=MediaPlayer.PlayState;if(_AB==0||_AB==1)
{MediaPlayer.Play();PlaySlide();return 1;}return 0;}}function MediaPlayer_Pause()
{if(ClientCaps & Player_70ObjectModel)
{var _AB=MediaPlayer.PlayState;if(_AB==1||_AB==10)
{MediaPlayer.Controls.Play();MediaPlayer.Controls.Pause();PauseSlide();return 1;}else if(_AB==3)
{MediaPlayer.Controls.Pause();PauseSlide();return 1;}return 0;}else
{var _AB=MediaPlayer.PlayState;if(_AB==0)
{MediaPlayer.Play();MediaPlayer.Pause();PauseSlide();return 1;}else if(_AB==2)
{MediaPlayer.Pause();PauseSlide();return 1;}return 0;}}function MediaPlayer_IsPlaying()
{if(ClientCaps & Player_70ObjectModel)
{var _AB=MediaPlayer.PlayState;if(_AB==3)
return 1;}else
{var _AB=MediaPlayer.PlayState;if(_AB==2)
return 1;}return 0;}function MediaPlayer_IsStopped()
{if(ClientCaps & Player_70ObjectModel)
{var _AB=MediaPlayer.PlayState;if(_AB==1||_AB==8||_AB==10)
return 1;}else
{var _AB=MediaPlayer.PlayState;if(_AB==0||_AB==8)
return 1;}return 0;}function MediaPlayer_Stop()
{if(ClientCaps & Player_70ObjectModel)
{MediaPlayer.Controls.Stop();}else
{MediaPlayer.Stop();}}function MediaPlayer_Previous()
{if(IsPresentationNotLocalOnNT4())
return;var _OB;_OB=_c(_UA,-1);if(_OB!=null)
{g_fSeekTimeWhenOpen=-1;g_nSeekEntryWhenOpen=-1;_q(_OB,0);}}function MediaPlayer_Next()
{if(IsPresentationNotLocalOnNT4())
return;var _LB;_LB=_c(_UA,1);if(_LB!=null)
{g_fSeekTimeWhenOpen=-1;g_nSeekEntryWhenOpen=-1;_q(_LB,0);}}function MediaPlayer_SkipForward()
{if(IsPresentationNotLocalOnNT4())
return;fTime=Math.min(GetPresentationTime()+10.0,g_nDuration);SetPresentationTime(fTime,0);if(fTime>=g_nDuration)
g_fSeekTimeWhenOpen=0.0;g_nSeekEntryWhenOpen=-1;g_fSeekTimeWhenOpen=-1;}function MediaPlayer_SkipBack()
{if(IsPresentationNotLocalOnNT4())
return;fTime=Math.max(GetPresentationTime()-10.0,0);SetPresentationTime(fTime,0);g_nSeekEntryWhenOpen=-1;g_fSeekTimeWhenOpen=-1;}function MediaPlayer_SetVolume(vol)
{try
{if(ClientCaps & Player_70ObjectModel)
MediaPlayer.settings.Volume=vol;else
MediaPlayer.Volume=-10000+(vol*-100);}catch (e)
{}}function MediaPlayer_GetVolume()
{if(ClientCaps & Player_70ObjectModel)
return MediaPlayer.settings.Volume;else
return 100-(MediaPlayer.Volume/-100);}var g_fVolumeSliderTracking=0;var CONST_VOLUMEBORDER=10;var g_dxRange;function Volume_SetCapture(bCapture)
{g_fVolumeSliderTracking=bCapture;if(bCapture)
VolumeDiv.setCapture();else
VolumeDiv.releaseCapture();}function MediaPlayer_ShowVolume(x,y)
{if(g_bPreviewMode)
return;VolumeDiv.style.left=_o(PlayerVolume)-40;VolumeDiv.style.top=_p(PlayerVolume);g_dxRange=VolumeBackground.width-2*CONST_VOLUMEBORDER;VolumeSlider.style.left=CONST_VOLUMEBORDER+MediaPlayer_GetVolume()*g_dxRange/100-(VolumeSlider.width/2);VolumeSlider.style.top=4;VolumeDiv.style.visibility="visible";VolumeDiv.focus();}function Volume_OnMouseLeave(ev)
{if(!g_fVolumeSliderTracking)
{VolumeDiv.style.visibility="hidden";if(g_oSCORMAPI)
g_oSCORMAPI.LMSSetValue("cmi.student_preference.audio",MediaPlayer_GetVolume().toString());WriteCookie(CONST_VOLUME_COOKIE,MediaPlayer_GetVolume().toString());}}function Volume_OnMouseMove(ev)
{if(g_fVolumeSliderTracking)
{xSlider=event.clientX+document.body.scrollLeft-GetStyleValue_Integer(VolumeDiv.style.left)-CONST_VOLUMEBORDER;if(xSlider<0)xSlider=0;if(xSlider>g_dxRange)xSlider=g_dxRange;VolumeSlider.style.left=xSlider+CONST_VOLUMEBORDER-(VolumeSlider.width/2);MediaPlayer_SetVolume(xSlider*100/g_dxRange);}}function Volume_OnMouseDown(ev)
{Volume_SetCapture(1);Volume_OnMouseMove(ev);}function Volume_OnMouseUp(ev)
{Volume_SetCapture(0);}function Volume_OnKeyDown(ev)
{if (event.keyCode!=37  &&
event.keyCode!=39)
{Volume_OnMouseLeave(event);return;}vol=MediaPlayer_GetVolume();if(event.keyCode==37)
vol-=10;else if(event.keyCode==39)
vol+=10;;if(vol<0)
vol=0;if(vol>100)
vol=100;MediaPlayer_SetVolume(vol);VolumeSlider.style.left=CONST_VOLUMEBORDER+MediaPlayer_GetVolume()*g_dxRange/100-(VolumeSlider.width/2);event.returnValue=0;}function MediaPlayer_SetButtonImageInternal(_HA,szBtnClass)
{_HA.className=szBtnClass;}function MediaPlayer_SetButtonImage(_HA,_SB)
{var szClass=_HA.id+"_"+_SB;if(_HA.id=="PlayerPlayPause")
{if(MediaPlayer_IsPlaying())
szClass="PlayerPause_"+_SB;else
szClass="PlayerPlayPause_"+_SB;}MediaPlayer_SetButtonImageInternal(_HA,szClass);}function MediaPlayer_ButtonRollOver(_HA)
{if(window.event&&_HA.contains(window.event.fromElement))
return 0;if(_HA.WMEnabled==0)
return;if(_HA.id=="PlayerPlayPause")
{if(_HA.className.indexOf("PlayerPause_")== -1)
window.status=g_szPlayStatus;else
window.status=g_szPauseStatus;}else if(_HA.id=="PlayerStop")
window.status=g_nPlayStatus;else if(_HA.id=="PlayerPrevious")
window.status=g_szPrevStatus;else if(_HA.id=="PlayerNext")
window.status=g_szNextStatus;else if(_HA.id=="PlayerSkipForward")
window.status=g_szSkipForwardStatus;else if(_HA.id=="PlayerSkipBack")
window.status=g_szSkipBackStatus;else if(_HA.id=="PlayerVolume")
window.status=g_szVolumeStatus;else if(_HA.id=="PlayerDiscussion")
window.status=g_szDiscussStatus;else
{}MediaPlayer_SetButtonImage(_HA,"Hover");}function MediaPlayer_ButtonRollOut(_HA)
{if(window.event&&_HA.contains(window.event.toElement))
return 0;window.status="";if(_HA.WMEnabled==0)
return;MediaPlayer_SetButtonImage(_HA,"Rest");}function MediaPlayer_OnMouseDown(_HA)
{if(event.type.toLowerCase()== "keydown")
if(event.keyCode!=13)
return;if(_HA.WMEnabled==0)
return;MediaPlayer_SetButtonImage(_HA,"Down");}function MediaPlayer_OnMouseUp(_HA)
{if(event.type.toLowerCase()== "keyup")
if(event.keyCode!=13)
return;if(_HA.WMEnabled==0)
return;MediaPlayer_SetButtonImage(_HA,"Rest");if(window.event&&_HA.contains(window.event.srcElement))
{if(_HA.id=="PlayerPlayPause")
{g_bPauseAfterBuffer=0;g_nIgnoreThisEvent=-1;MediaPlayer_PlayPause();if(MediaPlayer_IsPlaying())
window.status=g_szPauseStatus;else
window.status=g_szPlayStatus;}else if(_HA.id=="PlayerStop")
MediaPlayer_Stop();else if(_HA.id=="PlayerPrevious")
MediaPlayer_Previous();else if(_HA.id=="PlayerNext")
MediaPlayer_Next();else if(_HA.id=="PlayerSkipForward")
MediaPlayer_SkipForward();else if(_HA.id=="PlayerSkipBack")
MediaPlayer_SkipBack();else if(_HA.id=="PlayerVolume")
MediaPlayer_ShowVolume(event.clientX,event.clientY);else if(_HA.id=="PlayerDiscussion")
DiscussionToggle();else
{}}}function MediaPlayer_SetFilename(_ZB)
{if(ClientCaps & Player_70ObjectModel)
{var _XB=escape(MediaPlayer.URL);var _bB=escape(_ZB);if(_XB.search(_bB)== -1)
{MediaPlayer.URL=_ZB;}}else
{var _XB=escape(MediaPlayer.Filename);var _bB=escape(_ZB);if(_XB.search(_bB)== -1)
{MediaPlayer.Filename=_ZB;}}}function MediaPlayer_SetCurrentLocation(nEntry,fTime)
{var fEntryStartTime=0.0;if(!g_bPreviewMode&&!g_bPrerollOnlyMode)
{fEntryStartTime=FindTimeDeltaIntoMediaFile(fTime);}else
{fEntryStartTime=fTime;}var bAndPlay=MediaPlayer_IsPlaying();if(!g_bPreviewMode&&!MediaPlayer_IsCurrentEntry(nEntry))
{if(!bAndPlay)
{if((ClientCaps & Player_70ObjectModel)&& g_fStartingTime!=fTime)
{g_bPlayAfterBuffer=0;g_bPauseAfterBuffer=1;}MediaPlayer_Play();}else
{g_bPlayAfterBuffer=1;g_bPauseAfterBuffer=0;}}if(g_bPreviewMode||(!MediaPlayer_SetCurrentEntry(nEntry)))
{MediaPlayer_SetCurrentPosition(fEntryStartTime,bAndPlay);}else
{if(g_nSeekEntryWhenOpen==-1)
{g_nSeekEntryWhenOpen=nEntry;g_fSeekTimeWhenOpen=fTime;g_fIgnoreMessages=1;}}}function MediaPlayer_IsCurrentEntry(nEntry)
{if(nEntry==-1)
return 0;if(ClientCaps & Player_70ObjectModel)
{if(nEntry<MediaPlayer.currentPlaylist.count)
{if(MediaPlayer.currentMedia!=null)
{if(MediaPlayer.currentPlaylist.item(nEntry).isIdentical(MediaPlayer.currentMedia))
{return 1;}}}}else
{if(MediaPlayer_IsPlaying()&& nEntry<MediaPlayer.EntryCount)
{if((nEntry +1)== MediaPlayer.GetCurrentEntry())
{return 1;}}}return 0;}function MediaPlayer_SetCurrentEntry(nEntry)
{if(nEntry==-1)
return 0;if(!(ClientCaps & Player_CanScrub))
return 0;if(ClientCaps & Player_70ObjectModel)
{if(nEntry<MediaPlayer.currentPlaylist.count)
{if(MediaPlayer.currentMedia!=null)
{if(!MediaPlayer.currentPlaylist.item(nEntry).isIdentical(MediaPlayer.currentMedia))
{if(MediaPlayer_IsPlaying())
{MediaPlayer.controls.playItem(MediaPlayer.currentPlaylist.item(nEntry));}else
MediaPlayer.controls.currentItem=MediaPlayer.currentPlaylist.item(nEntry);return 1;}}}}else
{if(MediaPlayer_IsPlaying()&& nEntry<MediaPlayer.EntryCount)
{if((nEntry +1)!= MediaPlayer.GetCurrentEntry())
{MediaPlayer.SetCurrentEntry(nEntry+1);return 1;}}}return 0;}function MediaPlayer_GetCurrentEntry()
{if(ClientCaps & Player_70ObjectModel)
{var i,_cA=MediaPlayer.currentPlaylist.count;for(i=0;i<_cA;i++)
{if(MediaPlayer.currentMedia!=null)
if(MediaPlayer.currentPlaylist.item(i).isIdentical(MediaPlayer.currentMedia))
return i;}return 0;}else
{try
{return MediaPlayer.GetCurrentEntry()-1;}catch(e)
{return 0;}}}function MediaPlayer_PositionChange(fOldPos,fNewPos)
{MediaPlayer_UpdatePlayerClock(-1);SyncSlideAnimTime(fNewPos);}function MediaPlayer_PlayStateChange(lOldState,lNewState)
{if(ClientCaps & Player_70ObjectModel)
MediaPlayer_UpdateControls(lOldState);else
MediaPlayer_UpdateControls(lNewState);if(g_bPreviewMode)
{if(lNewState==2)
MediaPlayer_StartClock();else
MediaPlayer_StopClock();}if (g_oSCORMAPI &&
g_fFinished &&
((lOldState==10&&ClientCaps & Player_70ObjectModel) ||
((lNewState==0||lNewState==8)&&ClientCaps & Player_64ObjectModel)))
{g_oSCORMAPI.LMSSetValue("cmi.core.lesson_status","completed");}}function MediaPlayer_UpdateControls(playState)
{try
{var _RB=PlayerPlayPause.style.backgroundImage;if(((ClientCaps & Player_70ObjectModel)&& playState==3)||((ClientCaps & Player_64ObjectModel)&&playState==2))
{MediaPlayer_SetButtonImageInternal(PlayerPlayPause,"PlayerPause_Rest");PlaySlide();}else
{MediaPlayer_SetButtonImageInternal(PlayerPlayPause,"PlayerPlayPause_Rest");PauseSlide();}}catch(e)
{}}function MediaPlayer_UpdatePlayerClock()
{if(GetPresentationTime()>g_nDuration-2.0)
g_fFinished=1;if(!(ClientCaps & Browser_SupportsFancyPlayerButtons))
return
if(arguments.length)
{if(arguments[0]==-1)
g_nCurrentClock=GetPresentationTime();else
g_nCurrentClock=arguments[0];}PlayerClock.innerText=_BA(g_nCurrentClock)+" / "+g_szDuration;if(g_bCannotSeekYet)
{if(MediaPlayer_CanSeek())
{setTimeout("MediaPlayer_UpdateNextPrevButtons();",1);}}}function MediaPlayer_UpdateNextPrevButtons()
{if(!(ClientCaps & Browser_SupportsFancyPlayerButtons))
return;if(!g_rgTOC.length||_YA==g_rgTOC[0]||g_bCannotSeekYet)
{PlayerPrevious.WMEnabled=0;PlayerPrevious.style.cursor="default";try
{if(PlayerPrevious.filters.item(0).enabled==0)
{PlayerPrevious.filters.item(2).stop();PlayerPrevious.filters.item(2).apply();PlayerPrevious.filters.item(0).enabled=1;PlayerPrevious.filters.item(1).enabled=1;PlayerPrevious.filters.item(2).play();}}catch(e)
{ }}else
{PlayerPrevious.WMEnabled=1;PlayerPrevious.style.cursor="hand";try
{if(PlayerPrevious.filters.item(0).enabled==1)
{PlayerPrevious.filters.item(2).stop();PlayerPrevious.filters.item(2).apply();PlayerPrevious.filters.item(0).enabled=0;PlayerPrevious.filters.item(1).enabled=0;PlayerPrevious.filters.item(2).play();}}catch(e)
{ }}if(!g_rgTOC.length||_YA==g_rgTOC[g_rgTOC.length-1] ||g_bCannotSeekYet)
{PlayerNext.WMEnabled=0;PlayerNext.style.cursor="default";try
{if(PlayerNext.filters.item(0).enabled==0)
{PlayerNext.filters.item(2).stop();PlayerNext.filters.item(2).apply();PlayerNext.filters.item(0).enabled=1;PlayerNext.filters.item(1).enabled=1;PlayerNext.filters.item(2).play();}}catch(e)
{ }}else
{PlayerNext.WMEnabled=1;PlayerNext.style.cursor="hand";try
{if(PlayerNext.filters.item(0).enabled==1)
{PlayerNext.filters.item(2).stop();PlayerNext.filters.item(2).apply();PlayerNext.filters.item(0).enabled=0;PlayerNext.filters.item(1).enabled=0;PlayerNext.filters.item(2).play();}}catch(e)
{ }}try
{if(!g_bPreviewMode)
{PlayerVolume.WMEnabled=1;PlayerVolume.filters.item(2).stop();PlayerVolume.filters.item(2).apply();PlayerVolume.filters.item(0).enabled=0;PlayerVolume.filters.item(1).enabled=0;PlayerVolume.filters.item(2).play();}else
PlayerVolume.style.display="none";PlayerSkipForward.WMEnabled=1;PlayerSkipForward.filters.item(2).stop();PlayerSkipForward.filters.item(2).apply();PlayerSkipForward.filters.item(0).enabled=0;PlayerSkipForward.filters.item(1).enabled=0;PlayerSkipForward.filters.item(2).play();PlayerSkipBack.WMEnabled=1;PlayerSkipBack.filters.item(2).stop();PlayerSkipBack.filters.item(2).apply();PlayerSkipBack.filters.item(0).enabled=0;PlayerSkipBack.filters.item(1).enabled=0;PlayerSkipBack.filters.item(2).play();}catch(e)
{}}var iSlideParamNumber=-1;function GetSlideClickNumberFromEvent(_IB)
{var i;for(i=0;i<_IB.ParameterList.length;i++)
{var _eB,_gB,nType;nType=_IB.GetParamType(i);_eB=_IB.GetParamTagname(i);_gB=_IB.GetParamValue(i);if(nType==_D&&_eB=="#SLIDECLICK")
{var _xA=_gB.indexOf(",");if(_xA!=-1)
return parseInt(_gB.substr(0,_xA));}}return -1;}function FIsLegitimateAnimationEvent(tmEvent)
{if(_UA!=null)
{nID=_UA.nID;fFound=0;rtSlideStart=0.0;while(nID>=0&&rtSlideStart==0.0)
{if(GetSlideClickNumberFromEvent(_WA[nID])==0 &&
_WA[nID].fTime<=g_rtFilterAnimationEventsBefore)
rtSlideStart=_WA[nID].fTime;nID--;}return tmEvent>=rtSlideStart;}return 0;}function FIsLegitimateFrameChange(szFrame,strRenderEvent,fTime)
{var i,_cA=_WA.length;var strExpectedFile="";for(i=0;i<_cA&&_WA[i].fTime<=fTime;i++)
{param=_WA[i].GetParamByName(szFrame);if(param!=null)
strExpectedFile=Unescape(param._gB);}if(strExpectedFile!="")
{ichLastSlash=strRenderEvent.lastIndexOf("/");ichSecondLastSlash=strRenderEvent.substr(0,ichLastSlash-1).lastIndexOf("/");strRenderEvent =strRenderEvent.substr(ichSecondLastSlash);if(strExpectedFile.toUpperCase().indexOf(strRenderEvent.toUpperCase())>=0)
{if(szFrame=="SlidesFrame")
g_rtFilterAnimationEventsBefore=_UA.GetTime();return 1;}}return 0;}function MediaPlayer_ScriptCommand(scType,Param)
{ichPrerollDone=Param.indexOf("?PrerollDone");if(ichPrerollDone>0)
{g_bWebStreamPrerollDone=1;return;}ichFrame=Param.indexOf("TargetFrame");ichTemplate=Param.indexOf("TemplateChange");if((ichFrame>0||ichTemplate>0)&& !g_bWebStreamPrerollDone)
{setTimeout("MediaPlayer_ScriptCommand(\""+scType+"\",\""+Param+"\");",100);return;}if(ichFrame>0)
{szFrame=Param.substr(ichFrame+12).split('&')[0];if(_UA!=null)
{strRenderEvent=Param.substr(0,ichFrame-1);if(strRenderEvent.indexOf("ClickSlide.htm")<0&&!FIsLegitimateFrameChange(szFrame,strRenderEvent,GetPresentationTime()))
return;}g_bHandlingMarkerHitEvent=1;pTag=document.getElementById(szFrame);szURL=Param.substr(0,ichFrame-1);if(szURL.indexOf("ClickSlide.htm")>=0)
{tmEvent=ExtractURLParameter("time=",Param,CONST_PARAMTYPE_FLOAT,0.0);if(FIsLegitimateAnimationEvent(tmEvent))
window.setTimeout("WebStream_DoAnimationClick(\""+szURL+"\");",50);}else if(ExtractURLParameter("X=",Param,0,-1)>0&&ExtractURLParameter("Y=",Param,0,-1)>0)
{pTag.WMNextSrc=GetSlideImageHTML("",szURL,ExtractURLParameter("X=",Param,0,10),ExtractURLParameter("Y=",Param,0,10));pTag.src="";window.setTimeout("NavigateIFRAME(\""+pTag.id+"\");",10);}else
{pTag.WMNextSrc=szURL;window.setTimeout("NavigateIFRAME(\""+pTag.id+"\");",10);}g_bHandlingMarkerHitEvent=0;return;}else if(ichTemplate>0)
{if(_UA!=null)
{strRenderEvent=Param.substr(0,ichTemplate-1);strRenderEvent=(strRenderEvent.split('?'))[0];if(!FIsLegitimateFrameChange("LINKLAYOUT",strRenderEvent,GetPresentationTime()))
return;}g_bHandlingMarkerHitEvent=1;UpdateCSSFile(Param.substr(0,ichTemplate-1));g_bHandlingMarkerHitEvent=0;return;}if(g_fIgnoreMessages)
{return;}g_bHandlingMarkerHitEvent=1;if(scType=="EVAL")
{if(Param!="EVAL")
eval(Param);}g_bHandlingMarkerHitEvent=0;}function MediaPlayer_ErrorDescription()
{if(ClientCaps & Player_70ObjectModel)
return MediaPlayer.error.item(0).errorDescription;else
return MediaPlayer.ErrorDescription;}function MediaPlayer_ErrorCode()
{if(ClientCaps & Player_70ObjectModel)
return MediaPlayer.error.item(0).errorCode;else
return MediaPlayer.ErrorCode;}function ProfileSupportsWebStreaming(strProfileIndex)
{var i=0;for(i=0;i<g_rgWebStreamProfiles.length;i++)
if(g_rgWebStreamProfiles[i]==strProfileIndex)
return 1;return 0;}function ProfileIsWMV9(strProfileIndex)
{var i=0;for(i=0;i<g_rgWMV9Profiles.length;i++)
if(g_rgWMV9Profiles[i]==strProfileIndex)
return 1;return 0;}function FindTOCEntry(iTOCEntrySeek)
{var _IB=null,i,_lA=_WA.length,iTOCEntry=0;for(i=1;i<_lA;i++)
{_IB=_WA[i];if(_IB.GetTOCTitle()!=0&&++iTOCEntry==iTOCEntrySeek)
return _IB.fTime
}return 0.0;}function FindTimeDeltaIntoMediaFile(_GA)
{var _IB=null,i,_lA=_WA.length,fStartOfNewMediaFile,szCurrentASFFile;fStartOfNewMediaFile=0.0;g_nIgnoreThisEvent=1;szCurrentASFFile=_WA[0].GetParamByName("MediaPlayer").ArgumentList[0];for(i=1;i<_lA;i++)
{_IB=_WA[i];if(_IB.fTime>_GA)
break;var _MB=_IB.GetParamByName("MediaPlayer");if(_MB.ArgumentList[0]!=szCurrentASFFile)
{szCurrentASFFile=_MB.ArgumentList[0];fStartOfNewMediaFile=_IB.fTime;g_nIgnoreThisEvent=i;}}var fAns=_GA-fStartOfNewMediaFile;if(fAns<0.0)
fAns=0.0;return fAns;}function SetEvent(_pA)
{if(!g_bPreviewMode&&_pA==g_nIgnoreThisEvent)
{return;}_r(_pA,1);}function ItemNode()
{var i,_DB=arguments.length;if(_DB<3)
return;this.nID=arguments[0];if(typeof(this.nID)!= "number")
return;this.szSourceFile=arguments[1];if(typeof(this.szSourceFile)!= "string")
return;var pArgs=new Array();this.szSourceFile=FillArgumentArray(this.szSourceFile,pArgs);if(pArgs.length==3&&this.szSourceFile=="IMAGE")
{this.szPrerollFile=PrepareURL(MakeAbsolutePath(pArgs[0]));this.szSourceFile=GetSlideImageHTML(GetProjectPath(),pArgs[0],pArgs[1],pArgs[2]);}else
this.szSourceFile=MakeAbsolutePath(this.szSourceFile);this.nSize=arguments[2];if(typeof(this.nSize)!= "number")
return;this.rgDependancies=new Array();for(i=3;i<_DB;i++)
{this.rgDependancies[i-3]=arguments[i];}this.nTotalSize=-1;this.nDownloadStatus=_B;this.fEarliestTimeNeeded=-1;this.fLatestSendTime=-1;this.Download=_i;this.CalcTotalSizeAtTime=_h;this.IsNeededAfterEventID=ItemNode_IsNeededAfterEventID;this.nEventItemList=new Array();}function GetSlideImageHTML(strPathPrefix,strImageFilename,dxImageWidth,dyImageHeight)
{var _gB;if(!(ClientCaps & Browser_SupportsCustomCSSTags))
{_gB=CONST_IMAGE_SCRIPT_STATICSIZE;_gB=_gB.replace(new RegExp("%1!s!","i"),escape(PrepareURL(strPathPrefix+strImageFilename)));}else
{_gB =CONST_IMAGE_SCRIPT;if(strPathPrefix.substr(0,4).toLowerCase()=="http")
_gB=_gB.replace(new RegExp("%1!s!","i"),escape(PrepareURL(strPathPrefix+strImageFilename)));else
_gB=_gB.replace(new RegExp("%1!s!","i"),escape(PrepareURL(strPathPrefix+strImageFilename)));}_gB=_gB.replace(new RegExp("%2!s!","i"),dxImageWidth);_gB=_gB.replace(new RegExp("%3!s!","i"),dyImageHeight);_gB=_gB.replace(new RegExp("%2!s!","i"),dxImageWidth);_gB=_gB.replace(new RegExp("%3!s!","i"),dyImageHeight);return _gB;}function ItemNode_IsNeededAfterEventID(nID)
{if(nID==-1)
return 1;for(var i=0;i<this.nEventItemList.length;i++)
if(nID<=this.nEventItemList[i])
return 1;return 0;}function _h(fTime)
{if(this.nTotalSize==-1||(this.fEarliestTimeNeeded==-1||fTime<this.fEarliestTimeNeeded))
{var j,_eA;this.fEarliestTimeNeeded=fTime;this.nTotalSize=this.nSize;_eA=this.rgDependancies.length;for(j=0;j<_eA;j++)
{this.nTotalSize+=_XA[this.rgDependancies[j]].CalcTotalSizeAtTime(fTime);}return this.nTotalSize;}return 0;}function AddItem(pItemNode)
{_XA[_XA.length]=pItemNode;}function MakeAbsolutePath(_gB)
{var knExtensionLen=3;var szExt=_gB.substr(_gB.length-knExtensionLen,knExtensionLen).toLowerCase();if(_gB.indexOf(":")== -1 &&
_gB.charAt(0)!="/")
{if(szExt=="asx")
{return GetProjectPath()+g_szProfileIndex+_gB;}else
{return GetProjectPath()+_gB;}}return _gB;}function FillArgumentArray(_gB,pArguments)
{var _xA=_gB.indexOf("?,?");if(_xA!=-1)
{szArgument=_gB.substr(_xA+3);_gB=_gB.substr(0,_xA);while((_xA=szArgument.indexOf("?,?"))!=-1)
if(_xA!=-1)
{pArguments[pArguments.length]=szArgument.substr(0,_xA);szArgument=szArgument.substr(_xA+3);}pArguments[pArguments.length]=szArgument;}return _gB;}function _J(nType,szTagOrCommand,_gB,nItemNodeIndex,pArguments,fLocalFile)
{this.nType=nType;this.szTagOrCommand=szTagOrCommand;this._gB=_gB;this.nItemNodeIndex=nItemNodeIndex;this.fLocalFile=fLocalFile;var i;this.ArgumentList=new Array();for(i=0;i<pArguments.length;i++)
{this.ArgumentList[i]=pArguments[i];}}function EventNode()
{var i,_DB=arguments.length;if(_DB<2)
return;this.GetParamTagname=_U;this.GetParamValue=_V;this.GetParamType=EventNode_GetParamType;this.GetFileLocalValue=EventNode_GetFileLocalValue;this.GetParamArgument=EventNode_GetParamArgument;this.GetParamItemNodeIndex=EventNode_GetParamItemNodeIndex;this.GetParamByName=_T;this.GetMediaFilename=_R;this.GetMediaFileEntry=EventNode_GetMediaFileEntry;this.GetTOCTitle=_Y;this.GetTOCIndent=_X;this.GetTime=_Z;this.CalcTotalSize=_M;this.AreAllItemsDownloaded=_L;this.ApplyEventParam=_K;this.ExecuteEvent=_O;this.CueMediaFile=_N;this.ClickSlide=EventNode_ClickSlide;this.nID=arguments[0];if(typeof(this.nID)!= "number")
return;this.fTime=arguments[1];if(typeof(this.fTime)!= "number")
return;this.nRelativeSize=-1;this.ParameterList=new Array();for(i=2;i<_DB;i++)
{var _pA,nType,szTagOrCommand,_gB="",nItemNodeIndex=-1,szArgument,pArguments;var fLocalFile=0;var szParam=arguments[i];if(szParam.charAt(0)== "#")
{nType=_D;}else
{nType=_E;}_xA=szParam.indexOf("=");if(_xA!=-1)
{szTagOrCommand=szParam.substr(0,_xA);_gB=szParam.substr(_xA+1);if(_gB.charAt(0)== "<"&&(_xA=_gB.indexOf(">"))!=-1)
{var szIndex=_gB.substring(1,_xA);nItemNodeIndex=parseInt(szIndex);_gB=_XA[nItemNodeIndex].szSourceFile;nSep=szParam.indexOf(",");if(nSep!=-1)
{szIndex=szParam.substring(nSep+1);nItemNodeIndex=parseInt(szIndex);if(nSep>-1)
_gB=_gB+"////"+_XA[nItemNodeIndex].szSourceFile;}fLocalFile=1;}pArguments=new Array();_gB=FillArgumentArray(_gB,pArguments)
if(_gB=="LINK"&&pArguments.length==2)
{_gB=CONST_LINK_SCRIPT;_gB=_gB.replace(new RegExp("%1!s!","i"),pArguments[0]);_gB=_gB.replace(new RegExp("%2!s!","i"),pArguments[1]);nType=CONST_ENP_TAGSCRIPT;}else if(_gB=="IMAGE"&&pArguments.length==3)
{_gB=GetSlideImageHTML(GetProjectPath(),pArguments[0],pArguments[1],pArguments[2])
nType=CONST_ENP_TAGSCRIPT;fLocalFile=1;}else if(nType!=_D)
{_gB=PrepareURL(MakeAbsolutePath(_gB));}}else
szTagOrCommand=szParam;if(szTagOrCommand=="MediaPlayer")
{nType=CONST_ENP_MEDIA_FILE;if(g_szASXLocation!="")
_gB=g_szASXLocation;}this.ParameterList[i-2]=new _J(nType,szTagOrCommand,_gB,nItemNodeIndex,pArguments,fLocalFile);}}function _U(_BB)
{if(_BB>=this.ParameterList.length)
return;return this.ParameterList[_BB].szTagOrCommand;}function _V(_BB)
{if(_BB>=this.ParameterList.length)
return;return this.ParameterList[_BB]._gB;}function EventNode_GetFileLocalValue(_BB)
{if(_BB>=this.ParameterList.length)
return;return this.ParameterList[_BB].fLocalFile;}function EventNode_GetParamType(_BB)
{if(_BB>=this.ParameterList.length)
return;return this.ParameterList[_BB].nType;}function EventNode_GetParamArgument(_BB,nWhichArg)
{if(_BB>=this.ParameterList.length)
return;if(nWhichArg>=this.ParameterList[_BB].ArgumentList.length)
return;return this.ParameterList[_BB].ArgumentList[nWhichArg];}function _T(_hB)
{var i,re,_cA=this.ParameterList.length;re=new RegExp(_hB,"i");for(i=0;i<_cA;i++)
{var _xA;_xA=this.ParameterList[i].szTagOrCommand.search(re);if(_xA!=-1)
{return this.ParameterList[i];}}return null;}function EventNode_GetParamItemNodeIndex(_BB)
{if(_BB>=this.ParameterList.length)
return;return this.ParameterList[_BB].nItemNodeIndex;}function _N()
{if(g_bMediaFileCued)
return;var szParam;szParam=this.GetMediaFilename();if(szParam)
{MediaPlayer_SetFilename(szParam);}g_bMediaFileCued=1;return 0;}function _R()
{var _MB=this.GetParamByName("MediaPlayer");if(_MB)
return _MB._gB;else
return null;}function EventNode_GetMediaFileEntry()
{var _MB=this.GetParamByName("MediaPlayer");if(_MB)
{return parseInt(_MB.ArgumentList[CONST_ENPA_INDEX_MEDIA_ENTRY]);}return null;}function _Y()
{var _PB=this.GetParamByName("#TOCTitle"),i;if(_PB==null)
return 0;var _fB=_PB._gB;if(_fB)
{_fB=Unescape(_fB);var replaced="";var i;for(i=0;i<_fB.length;i++)
{if(_fB.charAt(i)== '<')
replaced+="&lt;";else
replaced+=_fB.charAt(i);}_fB=replaced;}return _fB;}function _X()
{var _IB=this.GetParamByName("#TOCIndent");if(_IB)
return _IB._gB;else
return 0
}function _Z()
{return this.fTime;}function _L()
{if(g_bPreviewMode)
return 1;var i,_cA=this.ParameterList.length;for(i=0;i<_cA;i++)
{var _xA;_xA=this.ParameterList[i].nItemNodeIndex;if(_xA!=-1)
{if(_XA[_xA].nDownloadStatus==_B)
return 0;}}return 1;}function _M()
{var i,_cA=this.ParameterList.length;this.nRelativeSize=0;for(i=0;i<_cA;i++)
{var _MB=this.ParameterList[i]
if(_MB.nItemNodeIndex!=-1)
{this.nRelativeSize+=_XA[_MB.nItemNodeIndex].CalcTotalSizeAtTime(this.fTime);_XA[_MB.nItemNodeIndex].nEventItemList[_XA[_MB.nItemNodeIndex].nEventItemList.length]=this.nID;}}}function _O(_CA)
{var i;setTimeout("_AA()",1);MediaPlayer_UpdatePlayerClock(-1);for(i=0;i<this.ParameterList.length;i++)
{var _eB,_gB,nType,fFileLocal;nType=this.GetParamType(i);_eB=this.GetParamTagname(i);_gB=this.GetParamValue(i);fFileLocal=this.GetFileLocalValue(i);if(nType==CONST_ENP_MEDIA_FILE)
{if(!_CA&&!g_bHandlingMarkerHitEvent)
{if(g_fSeekTimeWhenOpen>-1)
MediaPlayer_SetCurrentLocation(this.GetMediaFileEntry(),g_fSeekTimeWhenOpen);else
MediaPlayer_SetCurrentLocation(this.GetMediaFileEntry(),this.fTime);}}else if(nType==_D)
{if(_eB=="#EVAL")
{try
{eval(_gB);}catch(e)
{}}else if(_eB=="#SLIDECLICK"&&!g_bUseWebStream)
{var _xA=_gB.indexOf(",");if(_xA!=-1)
{var szArgument=_gB.substr(_xA+1);_gB=_gB.substr(0,_xA);this.ClickSlide(parseInt(_gB),parseInt(szArgument));}}}else if(!g_bUseWebStream||!fFileLocal)
{var j,pTag=null;for(j=0;j<g_rgEventTags.length;j++)
{if(g_rgEventTags[j].id==_eB)
{pTag=g_rgEventTags[j];break;}}if(!pTag)
{pTag=document.getElementById(_eB);if(!pTag)
return;g_rgEventTags[g_rgEventTags.length]=pTag;}var nNodeIndex=this.GetParamItemNodeIndex(i);if(nNodeIndex==-1||pTag.IndexNodeIndex!=nNodeIndex||g_bForceReload)
{this.ApplyEventParam(pTag,_gB,nType);pTag.IndexNodeIndex=nNodeIndex;}}}}function _K(pTag,_gB,nType)
{if(pTag!=null)
{if(pTag.nodeName.toUpperCase()== "IFRAME")
{if(_gB=="")
{if(!(ClientCaps & Browser_SupportsRuntimeStyle))
pTag.parentElement.currentStyle.visibility="hidden";else
pTag.parentElement.runtimeStyle.visibility="hidden";}else
{if(pTag.id=="SlidesFrame")
{fImage=1;szHTML=_gB;iSep=_gB.indexOf("////");if(iSep>-1)
{szHTML=_gB.substr(0,iSep);szImage=_gB.substr(iSep+4,_gB.length-iSep-4);fImage=0;}if(fImage&&1)
{var pFrame=document.getElementById(pTag.id);if(pFrame)
{pTag.WMNextSrc=_gB;pFrame.src=_gB;}return;}if(ClientCaps & Browser_SupportsPowerpointHTML)
{_gB=szHTML;if(Technology & Technology_Mac&&URLIsDBCS(_gB))
_gB=encodeURL(_gB);}else
{var pFrame=document.getElementById(pTag.id);if(pFrame)
pFrame.src="javascript:document.open();document.write(\"<HTML><BODY BGCOLOR=#FFFFFF><IMG width=100% height=100% style='position:absolute;top:0;left:0' src='"+szImage+"'></BODY></HTML>\");document.close();";return;}}if(!(ClientCaps & Browser_SupportsCustomCSSTags))
{var pFrame=document.getElementById(pTag.id);if(Technology & Technology_Mac&&URLIsDBCS(_gB))
_gB=encodeURL(_gB);if(pFrame)
pFrame.src=_gB;return;}if(g_bForceReload||pTag.WMNextSrc!=_gB||g_bStatic!=g_bLastSlideStatic)
{g_bForceReload=0;if(pTag.id!="SlidesFrame"||!_F())
{if(!(ClientCaps & Browser_SupportsRuntimeStyle))
pTag.parentElement.currentStyle.visibility="hidden";else
pTag.parentElement.runtimeStyle.visibility="hidden";}if(nType==CONST_ENP_TAGSCRIPT)
pTag.src="";pTag.WMNextSrc=_gB;if(_gB.indexOf("PreLoad()")!=-1)
{g_bStatic=0;g_iCurrentOnClickEvent=0;g_iCurrentSlide=-1;}else if(g_bStatic&&pTag.id=="SlidesFrame"&&nType!=CONST_ENP_TAGSCRIPT)
{pTag.WMNextSrc=pTag.WMNextSrc+"#0";}window.setTimeout("NavigateIFRAME(\""+pTag.id+"\");",50);g_bLastSlideStatic=g_bStatic;}}}else if(pTag.nodeName.toUpperCase()== "LINK")
{if(ClientCaps & Browser_SupportsNavigateCSS)
{g_bRecalcPlayerClockPosition=1;var i,pTags=document.all.tags("DIV");for(i=0;i<pTags.length;i++)
{var pDIV=pTags(i);pDIV.style.removeExpression("width");pDIV.style.removeExpression("height");}setTimeout("UpdateCSSFile(\""+_gB+"\");",1);}}else
{return 0;}return 1;}return 0;}function UpdateCSSFile(szVal)
{if(!(ClientCaps & Browser_SupportsNavigateCSS))
return;LINKLAYOUT.href=szVal;RemoveCustomDIVAttributes();g_bRecalcPlayerClockPosition=1;}function NavigateIFRAME(szFrameID)
{var pFrame=document.getElementById(szFrameID);if(pFrame)
{try
{if(pFrame.WMNextSrc.indexOf("javascript:")== 0 &&
pFrame.WMNextSrc.indexOf("PreLoad()")==-1)
{if(_F())
pFrame.contentWindow.navigate(pFrame.WMNextSrc);else
pFrame.navigate(pFrame.WMNextSrc);}else
pFrame.src=pFrame.WMNextSrc;}catch(e)
{window.setTimeout("NavigateIFRAME(\""+pFrame.id+"\");",100);}pFrame.parentElement.runtimeStyle.removeAttribute("visibility",0);}}function WebStream_DoAnimationClick(szURL)
{var pFrame=document.getElementById("SlidesCmd");if(pFrame)
{try
{if(pFrame.readyState!="complete"||document.getElementById("SlidesFrame").readyState!="complete")
{window.setTimeout("WebStream_DoAnimationClick(\""+szURL+"\");",100);return;}pFrame.src=Unescape(szURL);}catch(e)
{window.setTimeout("WebStream_DoAnimationClick(\""+szURL+"\");",100);}pFrame.parentElement.runtimeStyle.removeAttribute("visibility",0);}}function Slide_DelayClick(delayedAttempts)
{if(delayedAttempts>10)
return;var i=0;try
{if(GetSlidesFrame())
GetSlidesFrame().document.body.pptNext();}catch(e)
{setTimeout("Slide_DelayClick("+(delayedAttempts+1)+")",50);}}function EventNode_ClickSlide(iIndex,iSlide)
{if(!(ClientCaps & Browser_SupportsPPTSlideAnimations))
return;if(g_iCurrentSlide==iSlide)
{if(iIndex==0&&g_iCurrentOnClickEvent!=0)
{g_bStatic=0;g_bForceReload=1;g_iCurrentOnClickEvent=0;}else if(!g_bStatic&&g_iCurrentOnClickEvent<iIndex)
{var i;for(i=0;i<iIndex-g_iCurrentOnClickEvent;i++)
Slide_DelayClick(1);g_iCurrentOnClickEvent=iIndex;}}else if(iIndex==0)
{g_iCurrentOnClickEvent=0;g_iCurrentSlide=iSlide;g_bStatic=0;}else
{g_iCurrentOnClickEvent=-1;g_iCurrentSlide=iSlide;g_bStatic=1;}}function AddEvent(_JB)
{_WA[_WA.length]=_JB;}function SetPresentationTime(_GA,_CA)
{var _IB=null,i,_lA=_WA.length;_IB=_WA[0];for(i=1;i<_lA;i++)
{if(_WA[i].fTime>_GA)
{break;}_IB=_WA[i];}if(!g_bPreviewMode&&_GA!=0.0)
{if(ClientCaps & Player_70ObjectModel||_GA!=0.0)
g_fIgnoreMessages=1;if(ClientCaps & Player_64ObjectModel)
g_bPlayWhenOpen=1;}g_nSeekEntryWhenOpen=_IB.GetMediaFileEntry();g_fSeekTimeWhenOpen=_GA;InvalidateWebStreamPreroll();_q(_IB,_CA);}function GetPresentationTime()
{var fCurrentPosition=MediaPlayer_GetCurrentPosition();var nCurrentEntry=MediaPlayer_GetCurrentEntry();if(fCurrentPosition<=0.0||isNaN(fCurrentPosition))
fCurrentPosition=0.0;var i,nWMVCount=g_rgfWMVStartTimes.length;if(nCurrentEntry<0||nCurrentEntry>=nWMVCount)
fRetVal=fCurrentPosition;else
fRetVal=g_rgfWMVStartTimes[nCurrentEntry]+fCurrentPosition;if(fRetVal>g_nDuration)
fRetVal=g_nDuration;return fRetVal;}function _r(nID,_CA)
{var _cA=_WA.length;if(nID>=0&&nID<_cA)
{return _q(_WA[nID],_CA);}}function _q(_IB,_CA)
{if(_IB==null)
{return 0;}if(_UA&&!_CA)
{if(_IB.GetMediaFileEntry()== _UA.GetMediaFileEntry())
{var bCannotSeek=!MediaPlayer_CanSeek();if(g_bCannotSeekYet!=bCannotSeek)
setTimeout("MediaPlayer_UpdateNextPrevButtons();",1);if(bCannotSeek&&!MediaPlayer_IsStopped())
{return 0;}}}if(g_bUseBandwidthManagement&&_UA)
{if(_IB.nID!=_UA.nID+1)
{g_nSeekToEvent=_IB.nID;m_bNeedRebuildItemArray=1;}}_UA=_IB;_IB.ExecuteEvent(_CA);if(g_bUseBandwidthManagement&&!_IB.AreAllItemsDownloaded())
{g_bPausedForDownload=1;try
{setTimeout("MediaPlayer_Pause();",1);}catch(e)
{ }_n();_y();window.setTimeout("_m("+_CA+")",400,"JavaScript");}}function _m(_CA)
{if(!_UA.AreAllItemsDownloaded())
{window.setTimeout("_m("+_CA+")",400,"JavaScript");}else
{g_bPausedForDownload=0;MediaPlayer_Play();_UA.ExecuteEvent(_CA);}}function _c(_EB,_fA)
{var i,_cA=_WA.length;for(i=_EB.nID+_fA;i>=0&&i<_cA;i+=_fA)
{if(_WA[i].GetTOCTitle()!= 0)
{return _WA[i];}}if(_fA<0)
return _WA[0];else
return _WA[_cA-1];}function _o(elem)
{if(elem.offsetParent!=null)
return elem.offsetLeft+_o(elem.offsetParent);return elem.offsetLeft;}function _p(elem)
{if(elem.offsetParent!=null)
return elem.offsetTop+_p(elem.offsetParent);return elem.offsetTop;}function EllipsifyTOC(pSingleDiv)
{if(!(ClientCaps & Browser_EllipsifyTOCEntries))
return;var _iB=TOCContentDiv;var _mA=_o(TOCContentDiv);var _nA=_mA+TOCContentDiv.clientWidth;if(_nA==0)
return;if(!pSingleDiv)
{var divs=TOCContentDiv.all.tags("div"),i;for(i=0;i<divs.length;i++)
{var pDiv=divs[i];EllipsifyDiv(pDiv,_nA);}}else
{EllipsifyDiv(pSingleDiv,_nA);}}function EllipsifyDiv(pDiv,nParentLimitX)
{pDiv.innerHTML=_WA[parseInt(pDiv.WMEventID)].GetTOCTitle();var _GB=document.body.createTextRange();_GB.moveToElementText(pDiv);var _hA,_iA,bDoIt=0;_hA=_GB.boundingLeft;_iA=_hA+_GB.boundingWidth;if(_GB.boundingWidth==0)
return;while(_iA>nParentLimitX)
{_GB.moveEnd("word",-1);bDoIt=1;_iA=_hA+_GB.boundingWidth;}if(bDoIt)
{_GB.moveEnd("word",1);_iA=_hA+_GB.boundingWidth;while(_iA>nParentLimitX)
{_GB.moveEnd("character",-1);bDoIt=1;_iA=_hA+_GB.boundingWidth;}_GB.moveEnd("character",-2);pDiv.innerText=pDiv.innerText.substr(0,_GB.text.length)+"...";}}function _v()
{datObj=new Date("January 14,1969 05:05:00");szTest=datObj.toLocaleString();_bA=szTest.slice(szTest.lastIndexOf("05")+2,szTest.lastIndexOf("00"));}function _BA(tm)
{var nSeconds=tm;var nHours=Math.floor(nSeconds / 3600);nSeconds-=(nHours*3600);var nMins=Math.floor(nSeconds / 60);nSeconds=Math.round(nSeconds-(nMins*60));if(nSeconds==60)
{nSeconds=0;nMins++;}var szTime=nHours+_bA;if(nMins<10)
szTime+="0";szTime+=nMins+_bA;if(nSeconds<10)
szTime+="0";szTime+=nSeconds;return szTime;}function _z()
{if(g_bTOCGenerated)
return;var _IB,i,_cA=_WA.length,_WB,_fB,nStartTime=0,bFirstPass=1;_WB='';rgtmIndent=new Array();rgtmDur=new Array();for(i=0;i<MAX_TOC_INDENT;i++)
rgtmIndent[i]=g_nDuration;for(i=_cA-1;i>=0;i--)
{_IB=_WA[i];if(_IB.GetTOCTitle())
{iIndent=_IB.GetTOCIndent();var j,tmLast=rgtmIndent[iIndent];for(j=iIndent;j<MAX_TOC_INDENT;j++)
rgtmIndent[j]=_IB.GetTime();rgtmDur[i]=tmLast-_IB.GetTime();}}for(i=0;i<_cA;i++)
{_IB=_WA[i];_fB=_IB.GetTOCTitle();if(_fB)
{tm= _IB.GetTime();iIndent=_IB.GetTOCIndent();var _wA=iIndent*16;var _YB='TOC_ClickEntry('+_IB.nID.toString()+')';var szEventID=_IB.nID.toString();var szToolTip=_fB+","+g_szLength+" -- "+ _BA(rgtmDur[i]);var szCursor="";var nEntry=_IB.GetMediaFileEntry();if(!(ClientCaps & Player_CanScrub))
szCursor="cursor:default;"
_WB+='<div id=_TOC'+ szEventID+' WMEventID="'+szEventID+'" WMEntry='+nEntry+' class=TOCEntryNormal style="'+szCursor+'text-indent:'+ _wA +'px" NOWRAP title="'+szToolTip+'" onclick="'+ _YB+'" onkeydown="'+_YB+'" TABINDEX=1>'+_fB+'</div>';}}g_rgTOC=new Array();TOCContentDiv.innerHTML=_WB;var pDivs= TOCContentDiv.getElementsByTagName("DIV");for(i=0;i<pDivs.length;i++)
g_rgTOC[g_rgTOC.length]=pDivs[i];if(!FNetscapeClient())
g_rgTOC.sort(new Function("x","y","if (parseInt(x.WMEventID)<parseInt(y.WMEventID)) return -1;else return 1;"));else
{var i1,i2;for(i1=0;i1<g_rgTOC.length;i1++)
{for(i2=0;i2<g_rgTOC.length;i2++)
{if(parseInt(g_rgTOC[i1].WMEventID)<parseInt(g_rgTOC[i2].WMEventID))
{var tmp=g_rgTOC[i1];g_rgTOC[i1]=g_rgTOC[i2];g_rgTOC[i2]=tmp;}}}}g_bTOCGenerated=1;}function TOC_ClickEntry(nID)
{if(!(ClientCaps & Player_CanScrub))
return;if(event.type.toLowerCase()== "keydown")
if(event.keyCode!=13)
return;if(IsPresentationNotLocalOnNT4())
return;g_nIgnoreThisEvent=-1;g_fSeekTimeWhenOpen=-1;g_nSeekEntryWhenOpen=-1;_r(nID,0);InvalidateWebStreamPreroll();event.returnValue=0;}function _AA()
{var _IB=_UA;var pTag,i;for(i=g_rgTOC.length-1;i>=0;i--)
{if(_IB.nID>=parseInt(g_rgTOC[i].id.substr(4)))
{pTag=g_rgTOC[i];break;}}if(pTag==null&&g_rgTOC.length)
{pTag=g_rgTOC[0];}if(pTag!=null)
{if(_YA!=null)
_YA.className="TOCEntryNormal";pTag.className="TOCEntryNowPlaying";var _oA=TOCContentDiv.offsetHeight+TOCContentDiv.scrollTop;var nOffset=pTag.offsetTop+pTag.offsetHeight;if((nOffset-2)> _oA)
TOCContentDiv.scrollTop=nOffset-TOCContentDiv.offsetHeight;else
{if(pTag.offsetTop<TOCContentDiv.scrollTop)
{TOCContentDiv.scrollTop=pTag.offsetTop;}}EllipsifyTOC(_YA);_YA=pTag;EllipsifyTOC(pTag);try
{if(g_bPreviewMode)
pTag.blur();else
pTag.focus();}catch(e)
{ }}else
{}setTimeout("MediaPlayer_UpdateNextPrevButtons();",1);}function LinkLayout_OnReadyStateChange()
{if(g_nPlayStatus==CONST_PS_RUN)
{var _dB=LINKLAYOUT.readyState;if(_dB=="complete")
{setTimeout("window.onresize()",1);EllipsifyTOC();if(!_F())
{SlidesDiv.children.item("SlidesFrame").style.visibility=SlidesDiv.style.visibility;HTML1Div.children.item("HTML1Frame").style.visibility=HTML1Div.style.visibility;}}else if(_dB=="loading")
{}}}function SlidesFrame_OnReadyStateChange()
{var srcElement=window.event.srcElement
if(srcElement.readyState=="complete")
{SlidesDiv.style.visibility="visible";if(!MediaPlayer_IsPlaying())
setTimeout("PauseSlide();",100);}else
{SlidesDiv.style.visibility="hidden";}}function HTML1Frame_OnReadyStateChange()
{var _dB=window.event.srcElement.readyState;var srcElement=window.event.srcElement;if(srcElement.readyState=="complete")
{HTML1Div.style.visibility="visible";}else
{HTML1Div.style.visibility="hidden";}}function ChangeProfile(nProfileNum)
{if(g_szASXLocation&&g_szASXLocation.length>0)
return;var nOldProfileIndex=parseInt(g_szProfileIndex);if(nOldProfileIndex==nProfileNum)
return;UninitializeSCORM();var bOldProfileWasWebStreaming=ProfileSupportsWebStreaming(g_szProfileIndex);var szProfileNum=nProfileNum.toString();var nOldProfileIndexLen=g_szProfileIndex.length;var i;for(i=0;i<_WA.length;i++)
{_IB=_WA[i];var _MB=_IB.GetParamByName("MediaPlayer");if(_MB)
{var _pA=_MB._gB.lastIndexOf(g_szProfileIndex);var szNewValue=_MB._gB.substr(0,_pA)+szProfileNum+_MB._gB.substr(_pA+nOldProfileIndexLen);_MB._gB=szNewValue;}}g_szProfileIndex=szProfileNum;if(g_bUseWebStream&&bOldProfileWasWebStreaming&&!ProfileSupportsWebStreaming(szProfileNum))
{var nSepChar="#";if(window.location.hash&&window.location.hash.length)
nSepChar=";";window.location.href+=nSepChar+unescape(CONST_AUTO_START)+"1;"+unescape(CONST_PROFILE)+szProfileNum;window.location.reload(1);return;}else if (g_bUseBandwidthManagement &&
!g_bPreviewMode &&
ProfileSupportsWebStreaming(szProfileNum) &&
ClientCaps & Player_SupportsWebStreaming)
{g_bUseBandwidthManagement=0;}g_bMediaFileCued=0;_WA[g_fStartingEvent].CueMediaFile();InitializeSCORM();}function CloseBitrateWindow()
{if(g_pBitRateWindow)
{g_pBitRateWindow.close();g_pBitRateWindow=null;}}function ToggleBitrateWindow()
{if(g_pBitRateWindow)
{CloseBitrateWindow();}else
{document.cookie=CONST_PROFILE_COOKIE+"=0;expires=Fri,31 Dec 1999 23:59:59 GMT;";var szBitrate="";szBitrate+="javascript:document.write(\'";szBitrate+="<HTML><HEAD><TITLE>"+g_szLoadingChooseBitrate+"</TITLE>";szBitrate+="<STYLE> A {position:absolute;left:10;}</STYLE>";szBitrate+="<SCRIPT>";szBitrate+='function WPC(nProfile){ ';if(IEVersion()< 5.5)
szBitrate+="dialogArguments";else
szBitrate+="document";szBitrate+=".cookie=\""+CONST_PROFILE_COOKIE+"=\"+nProfile+\"\";";szBitrate+="window.event.returnValue=0;window.close();}";szBitrate+="</SCRIPT>";szBitrate+="<LINK id=LINKTHEME href=\"theme.css\" rel=\"stylesheet\" type=\"text/css\">";szBitrate+="</HEAD><BODY NOWRAP><DIV ID=LeftSideBackground style=\"width:100%;height:100%\"><CENTER><br>";var i;for(i=0;i<g_rgViewableProfiles.length;i++)
{szBitrate+="<A href=\"\" onclick=\"javascript:WPC("+i+");\" >";szBitrate+=g_rgViewableProfiles[i].toString()+CONST_KBPS;if(ProfileIsWMV9(i))
szBitrate+="  WMV9 ";else
szBitrate+="  WMV8 ";if(ProfileSupportsWebStreaming(i))
szBitrate+=" "+g_szRichMedia;szBitrate+="</A><BR>";}szBitrate+="</CENTER></DIV></BODY></HTML>\')";var _GB=document.body.createTextRange();_GB.moveToElementText(LoadingWaitDiv_Play);var nDlgHeight=_GB.boundingHeight;nDlgHeight*=g_rgViewableProfiles.length
var nDlgLeft=_o(LoadingWaitDiv_Bitrate)+window.screenLeft;var nDlgTop=_p(LoadingWaitDiv_Bitrate)+window.screenTop;var nDlgWidth=300;var sFeatures="dialogLeft:"+nDlgLeft+"px;dialogTop:"+nDlgTop+"px;dialogWidth:"+nDlgWidth+"px;dialogHeight:"+nDlgHeight+"px;help:no;scroll:no;resizable:yes;status:no;unadorned:yes";var retVal=showModalDialog(szBitrate,window.document,sFeatures);var szProfile=ReadCookie(CONST_PROFILE_COOKIE);if(szProfile!="")
{if(szProfile!=g_szProfileIndex)
{var nProfile=parseInt(szProfile);ChangeProfile(nProfile);ResetBitrateDiv();}StartPresentation();}else
{window.event.returnValue=0;}}}function ResetBitrateDiv()
{if(g_rgViewableProfiles.length>1)
{var szBitratePopupHTML='javascript:ToggleBitrateWindow()';var szHTML='';szHTML+=g_rgViewableProfiles[g_szProfileIndex]+CONST_KBPS;if(ProfileSupportsWebStreaming(g_szProfileIndex))
szHTML+="<br>"+g_szRichMedia;szHTML+='<br><a style="position:relative;z-index:1" href="" onclick="'+szBitratePopupHTML+'">'+Unescape(g_szLoadingChooseBitrate)+'</a>';LoadingWaitDiv_Bitrate.innerHTML=szHTML;}else
{LoadingWaitDiv_Bitrate.style.display="none";}}function CalculateBestProfileForBandwidth()
{if(m_bProfileInURLParam)
return;if(_PA<=0.0||g_rgViewableProfiles.length<=1)
return;var fKBitsPerSecond=(_PA*8) / 1024.0;var nChoosenProfile=-1,nChooseProfileKBPS=0.0;var i;for(i=0;i<g_rgViewableProfiles.length;i++)
{if(ProfileSupportsWebStreaming(i))
continue;var fProfileKBPS=parseFloat(g_rgViewableProfiles[i]);if(fProfileKBPS<_PA)
{if(nChoosenProfile==-1||fProfileKBPS>nChooseProfileKBPS)
{nChoosenProfile=i;nChooseProfileKBPS=fProfileKBPS;}}}if(nChoosenProfile!=-1)
{ChangeProfile(nChoosenProfile);}else
{}}function PrerollScreen_SetStatus()
{InitCustomDIVTagLists();if(g_nPlayStatus==CONST_PS_PREINIT||g_nPlayStatus==CONST_PS_INIT)
{_gB=CONST_PREROLL_IMAGE_SCRIPT;_gB=_gB.replace(new RegExp("%1!s!","i"),g_szLoadingImg);_gB=_gB.replace(new RegExp("%2!s!","i"),g_szLoadingImgWidth);_gB=_gB.replace(new RegExp("%3!s!","i"),g_szLoadingImgHeight);LoadingWaitDiv_ImgDiv.innerHTML=_gB;LoadingWaitDiv_TitleDiv.innerHTML=Unescape(g_szLoadingTitle);LoadingWaitDiv_PresenterDiv.innerHTML=Unescape(g_szLoadingPresenter);LoadingWaitDiv_DescDiv.innerHTML=Unescape(g_szLoadingDesc);if(g_bPrerollOnlyMode)
{LoadingWaitDiv_Play.innerHTML="";LoadingWaitDiv_Bitrate.innerHTML="";LoadingWaitDiv_Anm.src=CONST_PREROLL_IMGSTATIC;}else
{LoadingWaitDiv_Play.innerHTML=Unescape(g_szLoadingWait);LoadingWaitDiv_Play.title=Unescape(g_szLoadingWaitNoEscape);LoadingWaitDiv_Bitrate.innerHTML="";LoadingWaitDiv_Anm.src=CONST_PREROLL_ANIMATION;}LoadingWaitDiv_Play.className=CONST_PREROLL_LOADINGTEXT;if(g_szLoadingImg=="")
LoadingWaitDiv_ImgDiv.style.display="none";}else if(g_nPlayStatus==CONST_PS_READY)
{LoadingWaitDiv_Play.innerHTML=Unescape(g_szLoadingPlay);LoadingWaitDiv_Play.title=Unescape(g_szLoadingPlayNoEscape);g_bPausedForDownload=0;LoadingWaitDiv_Anm.src=CONST_PREROLL_IMGSTATIC;LoadingWaitDiv_Play.className=CONST_PREROLL_LOADEDTEXT;if(!g_szASXLocation||g_szASXLocation.length<=0)
{LoadingWaitDiv_Bitrate.className=CONST_PREROLL_LOADINGTEXT;ResetBitrateDiv();}try
{LoadingWaitDiv_A.focus();}catch(e)
{ }}else
{PlayerPlayPause.title=g_PlayPauseTip;PlayerPrevious.title=g_PreviousTip;PlayerNext.title=g_NextTip;PlayerSkipForward.title=g_SkipForwardTip;PlayerSkipBack.title=g_SkipBackTip;PlayerVolume.title=g_VolumeTip;if(g_szDiscussionServerURL.length&&!g_bPreviewMode)
{PlayerDiscussion.style.visibility="visible";PlayerDiscussion.title=g_DiscussionTip;}}setTimeout("window.onresize()",1);}function PrerollScreen_DisplayTags()
{if(!(ClientCaps & Browser_SupportsCustomCSSTags))
return 1;InitCustomDIVTagLists();if(g_nPlayStatus==CONST_PS_RUN||g_fCreatingThumbnail)
{if(g_rgrgCustomDIVLists["WMPrerollDisplay"])
{var i;for(i=0;g_rgrgCustomDIVLists&&i<g_rgrgCustomDIVLists["WMPrerollDisplay"].length;i++)
{var pTag=g_rgrgCustomDIVLists["WMPrerollDisplay"][i];if(pTag.currentStyle.WMPrerollDisplay=="inline")
pTag.style.display="none";else if(pTag.currentStyle.WMPrerollDisplay=="none")
pTag.style.display="inline";}if(!g_rgrgCustomDIVLists)
return 0;}}else
{if(g_rgrgCustomDIVLists["WMPrerollDisplay"])
{var i;for(i=0;g_rgrgCustomDIVLists&&i<g_rgrgCustomDIVLists["WMPrerollDisplay"].length;i++)
{var pTag=g_rgrgCustomDIVLists["WMPrerollDisplay"][i];if(pTag.currentStyle.WMPrerollDisplay=="inline")
pTag.style.display="inline";else if(pTag.currentStyle.WMPrerollDisplay=="none")
pTag.style.display="none";}if(!g_rgrgCustomDIVLists)
return 0;}}return 1;}function SetDynamicDivDimensions()
{if(!(ClientCaps & Browser_SupportsCustomCSSTags))
return;InitCustomDIVTagLists();var i;if(g_rgrgCustomDIVLists["WMBodyWidth"])
{for(i=0;i<g_rgrgCustomDIVLists["WMBodyWidth"].length;i++)
{var divtag=g_rgrgCustomDIVLists["WMBodyWidth"][i];var szVis=divtag.style.visibility;if(szVis.length&&szVis=="hidden")
continue;if(divtag.currentStyle.WMBodyWidth)
{divtag.runtimeStyle.width=document.body.clientWidth;}}}if(g_rgrgCustomDIVLists["WMBodyHeight"])
{for(i=0;i<g_rgrgCustomDIVLists["WMBodyHeight"].length;i++)
{var divtag=g_rgrgCustomDIVLists["WMBodyHeight"][i];var szVis=divtag.style.visibility;if(szVis.length&&szVis=="hidden")
continue;var nTop=GetStyleValue_Integer(divtag.currentStyle.top);var nOffset=GetStyleValue_Integer(divtag.currentStyle.WMBodyHeight);if(document.body.clientHeight>=nTop+nOffset)
{divtag.runtimeStyle.height=(document.body.clientHeight+document.body.scrollTop)-nTop-nOffset;}}}if(g_rgrgCustomDIVLists["WMParentHeight"])
{for(i=0;i<g_rgrgCustomDIVLists["WMParentHeight"].length;i++)
{var divtag=g_rgrgCustomDIVLists["WMParentHeight"][i];var _oA=GetStyleValue_Integer(divtag.parentElement.currentStyle.height);if(document.body.clientHeight>=1&&divtag.parentElement.style.visibility=="visible"&&_oA>=divtag.currentStyle.WMParentHeight)
{divtag.runtimeStyle.height=_oA-divtag.currentStyle.WMParentHeight;}}}if(DiscussionDiv.style.visibility=="visible")
{DiscussionGripImage.runtimeStyle.left=(document.body.clientWidth-CONST_DISCUSSION_GRIP_WIDTH) / 2;SetDivContentHeight();}}function GetStyleValue_Integer(tagVal)
{if(isNaN(parseInt(tagVal)))
{return 0;}else
{return parseInt(tagVal);}}function GetSlidesFrame()
{if(document.frames.SlidesFrame.contentWindow)
return document.frames.SlidesFrame.contentWindow;if(document.frames.SlidesFrame)
return document.frames.SlidesFrame;return null;}function SizeImage(image)
{W=document.getElementById("SlidesFrame").offsetWidth;H=document.getElementById("SlidesFrame").offsetHeight;if(image.iw)
{newW=image.iw;newH=image.ih;}else
{newW=image.width;newH=image.height;}f=(1.0*W)/newW;if(H<newH*f)
f=(1.0*H)/newH;if(W<newW||H<newH)
{newW=newW*f;newH=newH*f;}image.width=newW;image.height=newH;s=image.style;s.posWidth=newW;s.posHeight=newH;s.posLeft=(W-newW)/2;s.posTop=(H-newH)/2;}function SizeAndShowImage(image)
{SizeImage(image);image.style.visibility="visible";}function R()
{if(GetSlidesFrame()&& GetSlidesFrame().im)
SizeImage(GetSlidesFrame().im);}function PreLoad()
{if(GetSlidesFrame()&& GetSlidesFrame().im)
GetSlidesFrame().im.src=GetSlidesFrame().im.mysrc;else
setTimeout("PreLoad()",100);}function Load(image)
{if(image.style.visibility=="hidden")
{SizeImage(image);SizeImage(image);image.style.visibility="visible";}}function PrerollImageResize()
{var LoadingWaitDiv_Img;var LoadingWaitDiv;LoadingWaitDiv_Img=document.getElementById("LoadingWaitDiv_Img");LoadingWaitDiv=document.getElementById("LoadingWaitDiv");LoadingWaitDiv_Img.style.visibility="hidden";LoadingWaitDiv_Img.style.posWidth=g_szLoadingImgWidth;LoadingWaitDiv_Img.style.posHeight=g_szLoadingImgHeight;var _CB=document.body.clientWidth;_CB=_CB<=96 ? 96:_CB;var _oA=document.body.clientHeight-(LoadingWaitDiv.clientHeight-LoadingWaitDiv_Img.clientHeight);_oA=_oA<=96 ? 96:_oA;if(FNetscapeClient()|| FMacClient())
{_CB=480;_oA=360;}var nNewWidth=g_szLoadingImgWidth;var nNewHeight=g_szLoadingImgHeight;var fAspect=(1.0*_CB) / nNewWidth;if(_oA<nNewHeight*fAspect)
fAspect=(1.0*_oA) / nNewHeight;if(_CB<g_szLoadingImgWidth||_oA<g_szLoadingImgHeight)
{nNewWidth=nNewWidth*fAspect;nNewHeight=nNewHeight*fAspect;}var pImageStyle=LoadingWaitDiv_Img.style;pImageStyle.posWidth=nNewWidth;pImageStyle.posHeight=nNewHeight;if(FNetscapeClient()|| FMacClient())
{pImageStyle.width=nNewWidth;pImageStyle.height=nNewHeight;}LoadingWaitDiv_Img.style.visibility="visible";if(ClientCaps & Browser_SupportsExpressionsInCSS)
document.recalc(1);}var g_fHitRoot=0;function FindLMSAPI()
{g_fHitRoot=0;api=SearchLMSAPI(window);if(api!=null)
return api;return null;}function SearchLMSAPI(win)
{var api,iframe;try
{if(win.opener==null&&(win.parent==null||win.parent==win))
g_fHitRoot=1;if(win.API !=null)
{return win.API;}else if(!g_fHitRoot&&win.parent!=null&&win.parent!=win)
{api=SearchLMSAPI(win.parent);if(api!=null)
return api;}else if(!g_fHitRoot&&win.opener!=null)
{api=SearchLMSAPI(win.opener);if(api!=null)
return api;}else if(win.frames.length>0)
{for(iframe=0;iframe<win.frames.length;iframe++)
{api=SearchLMSAPI(win.frames[iframe]);if(api!=null)
return api;}}}catch(e)
{}return null;}function InitializeSCORM()
{g_oSCORMAPI= FindLMSAPI();if(g_oSCORMAPI!=null)
{g_oSCORMAPI.LMSInitialize("");g_oSCORMAPI.LMSSetValue("cmi.core.lesson_status","incomplete");}}function UninitializeSCORM()
{if(g_oSCORMAPI)
{g_oSCORMAPI.LMSFinish("");g_oSCORMAPI=null;}}